### ISSUE TITLE
ExplainExceptionTest is changing the context for subsequent tests

### ISSUE THREAD

**Issue by klahnakoski** [pyparsing/pyparsing#129]
The unittest.py test suite must be run in a particular order to pass.  This means there are some inter-dependencies between tests; not just any order will pass. This is a problem that should be fixed to help with https://github.com/orgs/pyparsing/teams/pyparsing-dev/discussions/5

I looked into one interfering test:  [HTMLStripperTest](https://github.com/pyparsing/pyparsing/blob/master/unitTests.py#L3759) will run fine on its own.  If [ExplainExceptionTest](https://github.com/pyparsing/pyparsing/blob/master/unitTests.py#L4638) is run before, then [HTMLStripperTest](https://github.com/pyparsing/pyparsing/blob/master/unitTests.py#L3759) will fail.  I do not know why yet; [maybe it is the Packrat?](https://github.com/pyparsing/pyparsing/blob/master/unitTests.py#L4662)

On a related note, [ExplainExceptionTest](https://github.com/pyparsing/pyparsing/blob/master/unitTests.py#L4638) does not seem to test anything; whether the parsing happens or not, the test does not fail.

**Comment by ptmcg** [comment]
This has been fixed on several levels:
- the refactoring of the unit tests has added a context restore call at the beginning of every test
- the call to enablePackrat() (which was the original problem) has been removed
- new asserts have been added to this test so that it actually evaluates the test behavior

To be released in 3.0.0

**Comment by ptmcg** [comment]
Changes released in 3.0.0a2
