### ISSUE TITLE
Enhance infixNotation() to handle operator "classes"

### ISSUE THREAD

**Issue by klahnakoski** [pyparsing/pyparsing#174]
It would be nice to group operators with equivalent precedence:  so it is easy to say `*` and `/` are applied left to right, and before `+`  and `-`, which are also applied left to right.

**Comment by ptmcg** [comment]
This can already be done - see this example: https://github.com/pyparsing/pyparsing/blob/master/examples/eval_arith.py#L137

Here is another sample code from a current project I'm working on (these operator specs are passed as the second argument to infixNotation):

        base_operator_specs = [
            ('-', 1, pp.opAssoc.RIGHT, self.ArithmeticUnaryOp),
            ('**', 2, pp.opAssoc.LEFT, self.ArithmeticBinaryOp),
            (pp.oneOf('* / mod × ÷'), 2, pp.opAssoc.LEFT, self.ArithmeticBinaryOp),
            (pp.oneOf('+ - −'), 2, pp.opAssoc.LEFT, self.ArithmeticBinaryOp),
            (pp.oneOf("< > <= >= == != ≠ ≤ ≥"), 2, pp.opAssoc.LEFT, BinaryComparison),
            ((BETWEEN | WITHIN, AND), 3, pp.opAssoc.LEFT, IntervalComparison),
            ((IN_RANGE_FROM, TO), 3, pp.opAssoc.LEFT, IntervalComparison),
            (NOT, 1, pp.opAssoc.RIGHT, UnaryNot),
            (AND | '∧', 2, pp.opAssoc.LEFT, BinaryComp),
            (OR | '∨', 2, pp.opAssoc.LEFT, BinaryComp),
            (('?', ':'), 3, pp.opAssoc.RIGHT, TernaryComp),
        ]

I believe that in C, '==' and '!=' have a lower precedence than the others. This would be easily addressed by just breaking up the single line into:

            (pp.oneOf("< > <= >= ≤ ≥"), 2, pp.opAssoc.LEFT, BinaryComparison),
            (pp.oneOf("== != ≠"), 2, pp.opAssoc.LEFT, BinaryComparison),

In your parser, you are creating the `infixNotation` list of operations by just going through the KNOWN_OPS, giving each operator its own precedence level, thus giving you the incorrect behavior.  You'll need to do more structuring of these operations so that operators of like precedence will be defined in the same entry (most like with a MatchFirst or Or), and then they will be handled properly left-to-right. Note that all operators at the same level will have to call the same parse action, so the parse action will need to perform the correct operation for each operand in turn.

**Comment by ptmcg** [comment]
Something like this would, I think, still fit into your infixNotation. The only wrinkle is how you will handle the ternary operator.

```
KNOWN_OPS = [
    Literal("||").setName("concat").setDebugActions(*debug),
    (Literal("+").setName("add").setDebugActions(*debug) | Literal("-").setName("sub").setDebugActions(*debug)),
    (Literal("*").setName("mul").setDebugActions(*debug) | Literal("/").setName("div").setDebugActions(*debug)),
    (Literal("+").setName("add").setDebugActions(*debug) | Literal("-").setName("sub").setDebugActions(*debug)),
    (Literal("<>").setName("neq").setDebugActions(*debug) |
     Literal(">").setName("gt").setDebugActions(*debug) |
     Literal("<").setName("lt").setDebugActions(*debug) |
     Literal(">=").setName("gte").setDebugActions(*debug) |
     Literal("<=").setName("lte").setDebugActions(*debug) |
     Literal("=").setName("eq").setDebugActions(*debug) |
     Literal("==").setName("eq").setDebugActions(*debug) |
     Literal("!=").setName("neq").setDebugActions(*debug)),
    #((BETWEEN.setName("between").setDebugActions(*debug), AND) |(NOT_BETWEEN.setName("not_between").setDebugActions(*debug), AND)),
    (IN.setName("in").setDebugActions(*debug) | NOT_IN.setName("nin").setDebugActions(*debug)),
    (IS_NOT.setName("neq").setDebugActions(*debug) | IS.setName("is").setDebugActions(*debug)),
    (LIKE.setName("like").setDebugActions(*debug) | NOT_LIKE.setName("nlike").setDebugActions(*debug)),
    AND.setName("and").setDebugActions(*debug)
    OR.setName("or").setDebugActions(*debug),
]

```

**Comment by klahnakoski** [comment]
Thank you very much for the prompt reply!
