### ISSUE TITLE
Parent element's `skipWhitespace` seems to determine whether to skip whitespace

### ISSUE THREAD

**Issue by TMiguelT** [pyparsing/pyparsing#203]
## Background
I have a segment of my grammar designed to match all the words on one line, ignoring initial whitespace. The grammar is:
```python
from pyparsing import *

tok = LineStart() + OneOrMore(Word(alphas))
test_string = '''
               some text on a line
          : more text on a line
'''
```

Now, if I try to actually match some text, this won't match because the first character of each line is whitespace, so `LineStart()` can't match:
```python
print(tok.searchString(test_string))
```

I can try to use `leaveWhitespace()` on the `LineStart()`, which seems to solve the issue. This is a bit strange considering `leaveWhitespace()` is "mostly used internally to the pyparsing module, rarely used by client code", but whatever, it works:
```python
tok = LineStart().leaveWhitespace() + OneOrMore(Word(alphas))
print(tok.searchString(test_string)[0])
```

## Issue

But now, I need to compose `tok` using an Or statement. This doesn't match the first line at all, even though it should, because `grammar` now has `skipWhitespace` set to True, even though `tok_a` has it as `False`:
```python
tok_a = LineStart().leaveWhitespace() + OneOrMore(Word(alphas))
tok_b = ':' + OneOrMore(Word(alphas))
grammar = tok_a ^ tok_b
grammar.searchString(test_string)
```

Alternatively if I set `grammar.leaveWhitespace()`, all the `Word()` tokens will fail to match because their parent element isn't skipping whitespace anymore, and the parent element, not the child, seems to determine whether they skip whitespace or not: 
```python
grammar.leaveWhitespace().searchString(test_string)
```

So in general, I'm finding it tricky to work around this behaviour whereby the parent elements are actually determining whether or not to skip whitespace.

**Comment by TMiguelT** [comment]
Oh, the solution to this is much simpler than I thought! It turns out that when you call [`leaveWhitespace()` on composite elements](https://github.com/pyparsing/pyparsing/blob/72f2c5a67b4a26f584104b9ff63e1f272f54c5df/pyparsing/core.py#L3017-L3024), it recursively sets `skipWhitespace = True` on *all* children. Which in some cases (e.g. the last snippet above) is not what you want.

I think the easy solution would be to add an optional flag to `leaveWhitespace(recursive=True)` that lets you set recursive to false.

**Comment by avm19** [comment]
A somewhat related issue is the difference in how `skipWhitespace` are defined in compound ParseElements:
- `pyparsing.And()` inherits `skipWhitespace` from the first component `exprs[0]`
- `pyparsing.Combine()` sets `skipWhitespace = True` overwriting the superclass-initialised value.

[On second thought, `pyparsing.Combine()` is not truly a compound expression, but still situation is confusing. ]

Perhaps, the logic of determining `skipWhitespace` should be left only to abstract classes, such as `ParseExpression`.

**Comment by ptmcg** [comment]
I think the docstring for Combine explains this:
```
    Converter to concatenate all matching tokens to a single string.
    By default, the matching patterns must also be contiguous in the
    input string; this can be disabled by specifying
    ``'adjacent=False'`` in the constructor.
```

To implement this, `Combine` calls `leaveWhitespace` on the contained expression (which recurses through all elements, thereby enforcing the absence of whitespace between them), and then resets its own whitespace policy back to skipping whitespace using a non-recursive attribute assignment `self.skipWhitespace = True`. You can then call `leaveWhitespace` on the `Combine` expression itself if that is required.

`ParseExpression` classes look at their content expressions to see whether skipping leading whitespace is desired. As you already discerned, `And` has to use the same value for `skipWhitespace` as its initial expression, otherwise an element with `leaveWhitespace()` will behave differently when used in an `And`, which is probably undesirable. `Or`, 'MatchFirst`, and `Each` all have to do more work, since match alternatives may not all share the same whitespace policy.

Thanks for posting this comment, by the way, it has helped clarify my thinking on TMiltonT's PR #219.
