### ISSUE TITLE
Bug in fourFn.py example

### ISSUE THREAD

**Issue by tvdmitrii** [pyparsing/pyparsing#207]
Hi!

# Bug
I found a little bug in fourFn.py, which prevents it from evaluating expressions that include functions of multiple variables. It treats every function defined in `fn = {...}` as a function of a single variable.

To reproduce the bug add `"multiply": lambda a, b: a*b` function to `fn = {...}`. Try to evaluate an expression which includes `multiply(3,7)` and you will encounter an error saying that argument b is missing.

# Fix
I believe that `len(t[0])` in line 83 should be replaced with `len(t[1])` like so:
```python
fn_call = (ident + lpar - Group(expr_list) + rpar).setParseAction(
    lambda t: t.insert(0, (t.pop(0), len(t[1])))
```

# Details
The lambda function takes `['multiply', '(', [['3'], ['7']], ')']` and turns it into `[('multiply', 1), '(', [['3'], ['7']], ')']`, where 1 is the number of arguments, which is wrong. The problem is that `(t.pop(0), len(t[0]))` takes length of `'('` and treats it as the number of arguments, which is wrong. It should be taking the length of `[['3'], ['7']],`, which is `t[1]`.

It works for functions of a single variable, because the length of `'('` is 1.

**Comment by ptmcg** [comment]
I cannot reproduce this problem. I added "multiply" as you suggested, and added a `test("multiply(3, 7)")` line and get this output:

    multiply(3, 7) = 21 [('multiply', 2), [['3'], ['7']]] => ['3', '7', ('multiply', 2)]

Note also that my output does not include any '(', ')' tokens, because they are suppressed in their definition on line 74. Is it possible that you made other changes to fourFn.py that result in this problem?

I *do* think that using a lambda for a parse action is a bad idea in an example, so I will change this to use a small explicit function instead. Then it would be easier to add print statements or debugging breakpoints to view the contents of the passed-in tokens. I'm also adding "hypot" to show an additional multi-argument function, and "all" to show a function with a variable number of arguments.

**Comment by tvdmitrii** [comment]
You are absolutely right! I haven't realized this, but I have introduced the error myself. () should be Suppressed. I should have tested it on the original copy. Sorry for wasting your time!
