### ISSUE TITLE
Railroad diagram future updates

### ISSUE THREAD

**Issue by multimeric** [pyparsing/pyparsing#226]
I'm making this issue so that I and anyone else can suggest improvements to the railroad diagram generation feature.

TODOs:
* [ ] (from #225) Suppress `FollowedBy`/`_FB` subclass
* [ ] Fix the root element not being called `Unnamed` and instead being called `Forward` e.g. in the SQL example
* [ ] Fix the root element not being labelled "root" as it was previously
* [ ] Consider ways to use the element class to disambiguate the Unnamed classes

**Comment by ptmcg** [comment]
`expr = expr1 + expr2 + expr3` will create `expr` as `And([And([expr1, expr2]), expr3])`.  If the sub exprs are "collapsible" , calling `expr.streamline()` will flatten `expr` to `And([expr1, expr2, expr3])`.  This might help in verticalizing `And` elements. Probably something to add to `to_railroad`.

**Comment by ptmcg** [comment]
I could see some value in including results names as some kind of annotation, perhaps as part of the label you attach in the dashed lines around the element. I could also see this as unwanted clutter to someone who just wants to see the structure of the parser. Perhaps a `show_results_names` option to `to_railroad`?

**Comment by TMiguelT** [comment]
Thank you, that's useful to know about `streamline()`, although there is actually a chance that the railroad library streamlines nested `And`s anyway, because to my knowledge railroad diagrams don't have such a concept. 

`resultName` is tricky, because it is indeed useful, but as I said above, I'm already cramming so many things into the "group" annotations that it might get cluttered. I suppose I could have a consistent format like `tokenName → resultsName`. Do you think that should be in the annotation (above the token), or in the textbox itself?

**Comment by ptmcg** [comment]
I just tried generating a diagram for the delta_time.py time_expression - very interesting. But it looks like streamline() doesn't make any difference.

On resultName, I too was thinking of something like a right arrow, but as I said, I could see some people wanting it and others not. So you could make it an argument to `to_railroad`, or just leave it out for now and see if anyone requests it. (And if `to_railroad` starts getting too many more args, it may be worth packaging as a Railroader object.

**Comment by ptmcg** [comment]
What do you think about breaking out named terminals (like Word and Regex) as their own sub-diags. I think their usages would be cleaner-looking. See this paste HTML: https://dpaste.com/DHHV86L5J where I tried to modify your code to break them out, but only got as far as replacing the names.  This diagram is for this little parser:

```
ppc = pp.pyparsing_common
alpha_word = pp.Word(pp.alphas, pp.alphanums + '-').setName("alpha_word")
switch_dev_port = pp.Group(alpha_word("switch")
                           + SLASH
                           + ppc.integer("device")
                           + SLASH
                           + ppc.integer("port")
                           ).setName("switch-dev-port")

flags = pp.oneOf("FA")
lag_line = (switch_dev_port("sdp")
            + alpha_word("flags")
            + alpha_word("state")
            + ppc.integer("priority")
            + ppc.integer("port")
            ).setName("lag_line")

```

**Comment by TMiguelT** [comment]
I've thought about doing this, I think it would help readability, but only if the tokens have custom names. Otherwise you end up with a lot of "unnamed" groups, and the diagram is even less readable than before. Can we rely on users to actually name everything?

**Comment by ptmcg** [comment]
No - only extract out the ones with names. I found myself, after creating a diagram that I was unhappy with, going back and adding names to get a good diagram. So the diagram actually helped me create better software. (I also changed the default name created for QuotedString - the previous one was rather verbose and ugly - again, the diagram process itself helped me improve my code.)

Also, if you move the name into the text of the element, now the surrounding dashed border could be used to indicate Group'ing, and could be annotated with a results name if one is specified, and there would not be confusion between results name and expression name.

I also went through a parser refactoring process when diagramming the delta_time.py example. The diagram helped me see that I had some duplicated sections in the parser that could be unified. I'm really very excited at how this tool will help me write better parsers.

-- Paul

**Comment by ptmcg** [comment]
Can you annotate a block without the dashed border? That could still be used to show a results name for elements that are not enclosed in a Group. And the Group would not need to be labeled "Group" - the dashed border would be a sufficient indication. And the Group had a results name, than that could be annotation outside the dashed border.

**Comment by TMiguelT** [comment]
> No - only extract out the ones with names.

Agreed, this could work. I think I do this kind of behaviour already for some other types of nodes

> So the diagram actually helped me create better software

Agreed! This also happened for my grammar

> Also, if you move the name into the text of the element, now the surrounding dashed border could be used to indicate Group'ing, and could be annotated with a results name if one is specified, and there would not be confusion between results name and expression name.

True, this will help address my concerns about the labels and dashed borders having a lot of meanings

> Can you annotate a block without the dashed border?

No, I think that's possible. The available components [are listed here](https://github.com/tabatkins/railroad-diagrams#components), and the only general annotation is using the `Group` element, as far as I know. So I know that you want a lot of complexity in terms of results names etc but I'm not certain that we have the tools to do so.

**Comment by ptmcg** [comment]
I think extraction of named terminals only needs to be done for a few expression classes: Word and Regex most notably, maybe Char, maybe CharsNotIn, maybe QuotedString. Not Literal or Keyword - their default names are pretty self-explanatory I think.

**Comment by ptmcg** [comment]
Looking forward to trying this out!!!

**Comment by TMiguelT** [comment]
Just to make sure, are you working on this regex extraction, or waiting for me to do it? If you're not, I'll get around to it but I can't prioritize it right now.

**Comment by ptmcg** [comment]
I took a run at it, and got the nodes relabeled, but I did not see where to wire in the logic to get the subdiagrams to be displayed. I can take another run at it, but like you, I have some other work that comes first. If I get to make some headway, I'll post an update here.

**Comment by TMiguelT** [comment]
I think all you have to do is mark the node for "extraction", which is what I use to mean when a node should be pulled into a subdiagram. For example: https://github.com/pyparsing/pyparsing/blob/de7c442afb95cff6120a26a4b2c1a43bd84cecbf/pyparsing/diagram/__init__.py#L323-L324.

I guess as soon as it gets added to the lookup (ie here: https://github.com/pyparsing/pyparsing/blob/de7c442afb95cff6120a26a4b2c1a43bd84cecbf/pyparsing/diagram/__init__.py#L374-L380), you could check if the node is a regex and then mark it for extraction.

**Comment by retsyo** [comment]
so, we can save USD$79 now ;)
https://www.redlake-tech.com/products/diagrammar-for-windows/

**Comment by ptmcg** [comment]
I am going to try to apply these mods this weekend before pushing out 3.0.0c1:
- make sub-diagrams for all named elements (even if only used once) and use the names as body text where used
- use group annotations to show results name
- (maybe) add coloring and remove quotes as discussed in #264

Since this release has taken so long (completely on me), I can now drop support for Python 3.5. So where you recommend using dataclasses, I'll make those changes too. 

If you want to work on this with me, that would be good too. I think simplest would be just to use a shared branch in the repo. I've started one called '226-railroad-updates'.

**Comment by multimeric** [comment]
These sound like good changes. To be clear, are you going to make the group label only ever refer to results? Because it would be good if it had an unambiguous meaning. 

> So where you recommend using dataclasses, I'll make those changes too.

I had a quick look just now, and I think all of the classes and namedtuples that I use could be more concisely represented as dataclasses.

**Comment by ptmcg** [comment]
Yes, the group annotation will *just* be for results names. I've taken it off the places where the class name (like "Suppress") was shown, so that it is just results names. [Hmmm, it turns out there is an exception, in the case of NotAny. There really isn't a good railroad diagram construct for a negative lookahead, so it shows the lookahead term as a group with the name NotAny.]

I'll push that code to that branch so you can look at it. I tried to follow your data structures, I hope I didn't kludge them up too badly.

I also need to cook up some examples using SkipTo and Each to see how well they work. Each seems to map well to the AlternatingSequence diagram element, but SkipTo is going to require some kind of hack, perhaps an element with a "..." label.

**Comment by ptmcg** [comment]
There is also a problem when there is Unicode in the text, which I run into when diagramming the chemical formula parser using subscripts (as in "C₆H₅OH"). I think this is actually a bug in railroad-diagrams. I tried xml escaping the Unicode characters , but rr-diags xml escaped it again! The bug is that their xml escape logic only escapes symbols like & in the ASCII range, not full Unicode. It is actually an easy transform.

**Comment by multimeric** [comment]
That all sounds good. I'll take a look at the diff when I get time (could you open a draft PR so I can review it?). Also have you tried opening a bug with the `railroad` module that's having trouble with unicode escaping?

**Comment by ptmcg** [comment]
I think this is mostly done, except for one thing that I can see. Forward expressions don't seem to be fully showing their contents. If you look at the output from simpleBool, the boolean_expression just shows 'or' term, when it should show 2 tracks: one for 'or' term  and one for '(' boolean_expression ')'.  And 'not' term should show 2 tracks, one for 'not' term and one for 'boolean operand'. I've puzzled at this for a while, but figured I'd step away for a bit. But otherwise, I like how the labels and results names are looking.

(I was actually pretty impressed with how infixNotation expressions came out - AND the diagram showed how I can simplify these expressions in an internal step!)

(I also see that there are a number of setName()s that need to be added in the examples, and setName removed from delimitedList. Of course, every time one of these changes, the test_diagram.py fails because the top-level number of diagrams changes.)

**Comment by ptmcg** [comment]
The Unicode problem appears to be a PyCharm issue. It occurs when I right click on the generated HTML and select "Open In.../Browser". If from the Windows File Explorer I just double click on the HTML file, it displays properly.

**Comment by ptmcg** [comment]
Massive changes, for the better! Thanks again for the daily collaboration!

Pushed out in 3.0.0rc1.
