### ISSUE TITLE
Unexpected behaviour with prefix expressions, `MatchFirst` and `parseAll=True`

### ISSUE THREAD

**Issue by ldbo** [pyparsing/pyparsing#230]
Hi,

The use of a `MatchFirst` combination of prefix expressions can result in a parsing error when used with `parseAll=True` depending on the order of the operands.

Let's consider the following expressions:
```python
exp1 = Word(alphas)
exp2 = "Foo" + Word(alphas)
com1 = exp1 | exp2
com2 = exp2 | exp1
```
Then, `com1.parseString("Foo bar", parseAll=True)` raises

```
ParseException: Expected end of text, found 'b'  (at char 4), (line:1, col:5)
```

whereas `com2.parseString("Foo bar", parseAll=True)` successfully returns a `ParseResult` represented by `(['Foo', 'bar'], {})`, as expected.

**Comment by ptmcg** [comment]
`MatchFirst` is order-dependent by design. In your `com1` example, a match is found for `exp1`, so that is sufficient to match the parsing requirement for the `MatchFirst` expression. Since 'bar' has not yet been parsed, the `parseAll = True` argument raises the `ParseException`.

To address this in your parser there are a couple of options:
 - manually order your alternatives from most-restrictive to least-restrictive, as you have done in `com2`
 - use the `"^"` operator instead of `"|"` in your grammar; pyparsing converts these to `Or` expressions instead of `MatchFirst`, and `Or` expressions will try to match _all_ alternatives and then selects the longest match (think of `Or` as `MatchLongest`)

(Note that `Or` expressions can incur a parse-time penalty - there are more notes on this on the [Performance-Tips](https://github.com/pyparsing/pyparsing/wiki/Performance-Tips) wiki page.

Thanks for trying out pyparsing!

**Comment by ldbo** [comment]
Thank for you answer !
