### ISSUE TITLE
"Backreference" as element name?

### ISSUE THREAD

**Issue by rav1e** [pyparsing/pyparsing#231]
Hello there,

Is there a way to use text matched by the parser as the name of a Group? For example, from:

```
(
  ( tree1
    (
      branch1
      (v1, v2)
    )
    (
      branch2
      (v3, v4)
    )
  )
)
```
Is it possible to get the following results without hard-coding the names:
```
{'tree1': {'branch1': [v1, v2]}
             {'branch2: [v3, v4]}}
```

Thanks, pyparsing is great!

**Comment by ptmcg** [comment]
Yes there is, that would be the `Dict` class. `Dict` is kind of an advanced feature to use, and usually takes a few tries to get things working right.

`Dict` should be able to be added completely after-the-fact. It takes a single expression argument, that of a repeated Group of expressions, where the first match in each parsed Group will be the key, and everything following will be the value.  So:

    from pyparsing import Suppress, Word, alphas, alphanums, printables, quotedString, delimitedList, Group, Dict
    LBRACE, RBRACE, EQ = map(Suppress, "{}=")
    key = Word(alphas, alphanums)
    value = quotedString | Word(printables, excludeChars=",}")
    simple_dict = LBRACE + delimitedList(Group(key + EQ + value)) + RBRACE

    sample = "{a = 100, b='xyz', c1=3.14159}"
    print(simple_dict.parseString(sample))

Prints:

    [['a', '100'], ['b', "'xyz'"], ['c1', '3.14159']]

Wrapping `simple_dict` in `Dict` (and using `dump()` to get the structure including results names):

    simple_dict = Dict(LBRACE + delimitedList(Group(key + EQ + value)) + RBRACE)
    print(simple_dict.parseString(sample).dump())

Prints:

    [['a', '100'], ['b', "'xyz'"], ['c1', '3.14159']]
    - a: '100'
    - b: "'xyz'"
    - c1: '3.14159'

Your format is a _little_ tricky, since you don't know if, after matching the first word in parentheses whether it is going to be a comma-delimited list of names or the first name of a subgroup. Also, we have to use a `Forward` since what you are parsing is a potentially recursive structure (so the `Dict` has to be included within the `Forward` so as to get the nested name assignments). But other than that, this follows a pretty straightforward and `Dict` -friendly form.

Just to make sure it would work, here is a bare-bones prototype:

    import pyparsing as pp

    LPAR, RPAR = map(pp.Suppress, "()")

    nested_tuple = pp.Forward()

    element = pp.Word(pp.alphas, pp.alphanums)
    element_tuple = LPAR + pp.Optional(pp.delimitedList(element)) + RPAR
    group_name = element + pp.FollowedBy(LPAR)
    nested_tuple <<= pp.Dict(pp.Group(LPAR
                                      + group_name
                                      + (nested_tuple | element_tuple)[1, ...]
                                      + RPAR))


    result = (LPAR + nested_tuple + RPAR).parseString(sample)

    # dump out the results in pyparsing dump format
    print(result.dump())

    # pretty-print results as a nested dict
    from pprint import pprint
    pprint(result.asDict(), width=20)

Prints:

```
[['tree1', ['branch1', 'v1', 'v2'], ['branch2', 'v3', 'v4']]]
- tree1: [['branch1', 'v1', 'v2'], ['branch2', 'v3', 'v4']]
  - branch1: ['v1', 'v2']
  - branch2: ['v3', 'v4']

{'tree1': {'branch1': ['v1',
                       'v2'],
           'branch2': ['v3',
                       'v4']}}
```
And you can write:

    print(result.tree1.branch1)

and get:

    ['v1', 'v2']

Good luck, glad you are enjoying pyparsing!

**Comment by rav1e** [comment]
Great! Many thanks for the very detailed response!
