### ISSUE TITLE
Exception about railroad in 3.0.0.a2

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#234]
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    from pyparsing.diagram import to_railroad, railroad_to_html
  File "/usr/local/lib/python3.6/site-packages/pyparsing-3.0.0a2-py3.6.egg/pyparsing/diagram/__init__.py", line 24, in <module>
    [("name", str), ("diagram", Optional[railroad.DiagramItem]), ("index", int)],
AttributeError: module 'railroad' has no attribute 'DiagramItem'

**Comment by ptmcg** [comment]
I'm not seeing this in the CI output, nor in my testing on my own system (Python 3.8). Can you give some more detail on what you are doing that fails? Perhaps include at least the beginning of `1.py` leading up to the failing import.

**Comment by yldiscover** [comment]
I am using py3:
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

Here is the 1.py:
import pyparsing as pp
from pyparsing.diagram import to_railroad, railroad_to_html
from pathlib import Path

# define a simple grammar for parsing street addresses such
# as "123 Main Street"
#     number word...
number = pp.Word(pp.nums).setName("number")
name = pp.Word(pp.alphas).setName("word")[1, ...]

parser = number("house_number") + name("street")
parser.setName("street address")

# construct railroad track diagram for this parser and
# save as HTML
rr = to_railroad(parser)
Path('parser_rr_diag.html').write_text(railroad_to_html(rr))

**Comment by ptmcg** [comment]
I assume your code is this:
``` python
import pyparsing as pp
from pyparsing.diagram import to_railroad, railroad_to_html
from pathlib import Path

# define a simple grammar for parsing street addresses such as "123 Main Street"
# number word...
number = pp.Word(pp.nums).setName("number")
name = pp.Word(pp.alphas).setName("word")[1, ...]

parser = number("house_number") + name("street")
parser.setName("street address")

# construct railroad track diagram for this parser and save as HTML
rr = to_railroad(parser)
Path('parser_rr_diag.html').write_text(railroad_to_html(rr))

```
Which generates this diagram for me successfully:
![street_address_rr_diag](https://user-images.githubusercontent.com/383875/90326561-57ff9700-df4f-11ea-850d-ffe8ff1a52f3.jpg)

It is possible that this works because I am using the current code that is in GitHub, which has some changes since pyparsing 3.0.0a2. I'll try to get that released to PyPI very soon.

**Comment by TMiguelT** [comment]
I've seen issues like this when you have defined your own module called `railroad.py` in the current working directory, meaning that PyParsing tries to `import railroad`, and accidentally imports *your* module, which doesn't contain what it expects. In this case you should rename `railroad.py` to something else.

**Comment by ptmcg** [comment]
It's possible, I'll double-check.

**Comment by ralienpp** [comment]
After getting a hint in #264 I ended up with the error described in this issue. The cause of the problem is very simple: I installed a package called `railroad`, which indeed does _not_ contain `DiagramItem`.

The solution is to pay close attention to what you're actually installing, it has to be `railroad-diagrams`. `setup.py` does everything correctly; but I ended up with the wrong library because I was tinkering with different versions of Python and different versions of `pyparsing` in the context of #264.

**Comment by TMiguelT** [comment]
Good hint for future users, thank you. But I recommend that, rather than installing the diagram package directly, you instead `pip install pyparsing[diagrams]` as is described in the documentation.

**Comment by RavenKiller** [comment]
@ptmcg I wonder how to make grammars as seperated sub-diagrams like yours. My program just put all grammars into one railroad and label them using their names.
![Snipaste_2021-04-28_14-26-54](https://user-images.githubusercontent.com/41775391/116356875-69af7300-a82e-11eb-825c-22f75b7fc6d3.png)

**Comment by multimeric** [comment]
Please make a separate issue for this question, and I will be happy to answer.

**Comment by ptmcg** [comment]
Pushed out in 3.0.0rc1. (Exception message when calling create_diagram without the necessary modules installed instructs that you `pip install pyparsing[diagrams]`.)
