### ISSUE TITLE
What is the differece between "<<" and "<<="?

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#235]
Hi,
 What is the differece between "<<" and "<<="?
 I found the "<<=" symbol in lua_parser.py, but I can not understand its usage.

**Comment by ptmcg** [comment]
I originally chose `<<` as the operator to insert an expression into a previously defined Forward, but this caused issues due to precedence of operations:

    fwd << this_expr | that_expr

incorrectly inserts only `this_expr` into `fwd`, since `<<` take precedence over `|`.  You can fix it by doing `fwd << (this_expr | that_expr)`, but it is easily overlooked.

I later added `<<=` to prevent this problem; `|` has precedence over `<<=`, so the `fwd` gets defined properly.

I actually removed `<<` after doing this, but reinstated it so that it could be used in the body of a Python lambda function (which only permits expressions, not statements).

More on other pyparsing operator descriptions can be found here: https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#expression-operators
