### ISSUE TITLE
Lazy repeat?

### ISSUE THREAD

**Issue by multimeric** [pyparsing/pyparsing#239]
PyParsing has `OneOrMore()`/`ZeroOrMore()` constructs which support repeats, but these are greedy, ie they will repeat as much as possible. Does PyParsing support a lazy repeat, ie "repeat as few times as possible"? This is equivalent to regex's `*` (greedy) vs `*?` (lazy)

**Comment by ptmcg** [comment]
Pyparsing is purely left-to-right parsing, with no implicit lookahead or backtracking.

Say you used this regex `r"'.*'"` to find a quoted string in `I think 'I am sorry' is a good apology, don't you?` this would give `'I am sorry' is a good apology, don'`. For regex to do this kind of greedy match, it has to read from the first matching `'` all the way to the end of the string, and then backtrack to the last matching `'`.

So when you say "as few times as possible", you are really telling regex "as few times as possible, as long as I can then match the next thing," and that's why backtracking in regex makes `.*?` work.

If you did something comparable in pyparsing, it would be 

    quoted_string = "'" + ZeroOrMore(Char(printables)) + "'"

which would also read the entire rest of the string in the `ZeroOrMore`, but then fail trying to match the `'`, and so this match would fail. So in a sense, pyparsing's repetitions *are* like greediness in regex, but without the added backtracking.

You can modify the repetition in `ZeroOrMore` and `OneOrMore` using a negative lookahead.

    quoted_string = ("'" 
                     + ZeroOrMore(~Literal("'") + Char(printables)) 
                     + "'")

Or using more recent notation:

    quoted_string = ("'" 
                     + ZeroOrMore(Char(printables), stopOn="'") 
                     + "'")

Now this behavior works similarly to what you would get with `'.*?'`.

I see this a lot in pyparsing grammars when people write expressions like:

    START, END = map(Literal, "START END".split())
    block = START + ZeroOrMore(Word(alphas)) + END

when the terminating word also matches the repetition expression, in this case `Literal("END")` and `Word(alphas)`. Using `stopOn` keyword to `ZeroOrMore` and `OneOrMore`, you would write it as:

    block = START + ZeroOrMore(Word(alphas), stopOn=END) + END

Does this help in your quest?

**Comment by TMiguelT** [comment]
The negative lookahead is an interesting pattern, I wonder if it should be formalised into an element? This might be the right solution to my problem but I'm struggling to apply it. 

My current dilemma is that I want to have the slash character delimit items in a list, but also be allowed within that list. I hope to parse:
```
'-o/--offrate' → ['-o', '--offrate']
'--off/rate' → ['--off/rate']
```
With the original grammar, I get:
```
>>> body = originalTextFor('-' + Optional('-') + OneOrMore(Char(alphas + '/')))
>>> list = body + ZeroOrMore('/' + body)
>>> list.parseString('-o/--offrate')
(['-o/'], {})  # This is wrong
>>> list.parseString('--off/rate')
(['--off/rate'], {})
```
If I add the `stopOn`, I get the inverse results:
```
>>> body = originalTextFor('-' + Optional('-') + OneOrMore(Char(alphas + '/'), stopOn='/'))
>>> list = body + ZeroOrMore('/' + body)
>>> list.parseString('-o/--offrate')
(['-o', '/', '--offrate'], {})
>>> list.parseString('--off/rate')
(['--off'], {})  # This is wrong
```

**Comment by ptmcg** [comment]
The issue with your using '/' within an item is that it must only be allowed if it is embedded in the item. You can't allow for an item to end with a '/', too easily confused with the delimiting '/' of the list. I was able to do this with a slight modification to `body` - I defined "embedded" as "followed by an alpha character":

    body = originalTextFor('-' + Optional('-') + OneOrMore(Char(alphas) | ('/' + FollowedBy(Char(alphas)))))

This will only accept a '/' if it is detected to be within the body, i.e., followed by an alpha character.

I tried a slightly different look at this, using delimited lists. In this case, the `delimitedList` in the switch expression takes care of the embeddedness testing, treating the '/' as a delimiter, and thus only valid if followed by another list element:

    switch = delimitedList(Word(alphas), '/', combine=True)
    body = Combine(Char('-')[1, 2] + switch)
    list = delimitedList(body, "/")
    
    list.runTests("""\
        -o/--offrate
        --off/rate
    """)

Gives:

```
-o/--offrate
['-o', '/', '--offrate']

--off/rate
['--off/rate']

```

**Comment by TMiguelT** [comment]
I like the look of this second option, using `delimitedList`. I'll give it a try once I can grasp how it works.

In any case, thank you for both of your comprehensive replies, you've given me a good place to start with this pattern.

**Comment by ptmcg** [comment]
I also recommend `delimitedList` with `combine=True` for dot-qualified variable names such as "namespace.var.attribute". So often I see people write:

    identifier = Word(alphanums+"_.")

which *works*, but also matches any unsigned integer, any unsigned real number, and even just plain "." or "....".

Or only slightly better:

    identifier = Word(alphas + "_", alphanums + "_.")

which enforces that the identifier starts with an alpha or "_", but also accepts "x..y......z....".

Using this:

    identifier_part = Word(alphas + "_", alphanums + "_")
    identifier = delimitedList(identifier_part, ".", combine=True)

is the preferred form.
