### ISSUE TITLE
question about quotedstring

### ISSUE THREAD

**Issue by yldiscover** [pyparsing/pyparsing#241]
Hi,
  A = 'abc'
  B = 'abc\\'
  D= 'abc\\\\'

 who to match all above three string with quotedstring?

**Comment by ptmcg** [comment]
Please show more complete code, including the input text you are trying to parse, the resulting text you think you should get, and ideally the parseString command you are using to parse it.  For instance, if you are trying to call `quotedString.parseString(A)`, then this will fail because `A` is just the character string `abc` with no quotes.

**Comment by yldiscover** [comment]
import os,sys,time,re
import pprint
from pyparsing import *
string_ = quotedString
def p( x ):
      sexpr = string_.parseString( x )
      pprint.pprint( sexpr.asList() )
x = open("1.t").readline().strip()
p( x )

#the string A,B,C is saved in 1.t
but get this exception:

Traceback (most recent call last):
  File "p5.py", line 30, in <module>
    p( x )
  File "p5.py", line 13, in p
    sexpr = string_.parseString( x )
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
pyparsing.ParseException: Expected {{Re:('"(?:[^"\\n\\r\\\\]|(?:"")|(?:\\\\(?:[^x]|x[0-9a-fA-F]+)))*') """} | {Re:("'(?:[^'\\n\\r\\\\]|(?:'')|(?:\\\\(?:[^x]|x[0-9a-fA-F]+)))*") "'"}}, found end of text  (at char 6), (line:1, col:7)

**Comment by ptmcg** [comment]
Please take the time to format your posts so that code is formatted as code. Indentation in Python is a significant feature.
Compare your post with this (which I am guessing is the correct indentation):

================
```
import os,sys,time,re
import pprint
from pyparsing import *
string_ = quotedString

def p( x ):
    sexpr = string_.parseString( x )
    pprint.pprint( sexpr.asList() )

x = open("1.t").readline().strip()
p( x )

```
#the string A,B,C is saved in 1.t
but get this exception:

```
Traceback (most recent call last):
File "p5.py", line 30, in
p( x )
File "p5.py", line 13, in p
sexpr = string_.parseString( x )
File "/usr/lib/python2.7/site-packages/pyparsing.py", line 1955, in parseString
raise exc
pyparsing.ParseException: Expected {{Re:('"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))') """} | {Re:("'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))") "'"}}, found end of text (at char 6), (line:1, col:7)

```
================

Formatting a question for ease of reading and understanding is a simple courtesy to those you are asking to help you.

Also, it is best to not post example code that relies on external files. For such a small example, just make the input text a `"""` string in the example itself.

Why not add a `print` statement inside your `p` function and see what you are actually trying to parse in that `x` variable (hint: `print(repr(x))` instead of just `print(x)`)?  I also encourage you to use pyparsing's `runTests` method: https://pyparsing-docs.readthedocs.io/en/pyparsing_2.4.7/pyparsing.html?highlight=runTests#pyparsing.ParserElement.runTests

**Comment by yldiscover** [comment]
`
import pprint

from pyparsing import *

string_ = quotedString

def p( x ):
      sexpr = string_.parseString( x )
      print repr(x)
      pprint.pprint( sexpr.asList() )

x = """
abc\"
"""

p( x )
`

**Comment by ptmcg** [comment]
To embed a '\' into a string literal, you must either escape it as `\\` or precede the quotes with `r`, as in `r"this has a \ in it"` (this notation is called a "raw string", though I prefer to call them "raw string literals" because they are no different from other strings, just different in how the interpreter reads them). I usually use the raw string literal form, since I hate typing '\'s.

`x` may **be** a Python quoted string, but it does not **contain** a quoted string for pyparsing to parse. There is no opening quote character, and the closing quote character is escaped (or it will be once you add the leading `r`).  Here is a valid call to parse string:

    print(quotedString.parseString("'this is a quoted string, in single quotes'"))
    print(quotedString.parseString('"this is another quoted string, in double quotes"'))
    print(quotedString.parseString(r'"this quoted string has an escaped double quote at the end \""'))
    print(quotedString.parseString(r'"this quoted string has an escaped double quote at the end so it will fail to parse \"'))

Or using runTests, it looks like:

    quotedString.runTests(r"""
        'this is a quoted string, in single quotes'
        "this is another quoted string, in double quotes"
        "this quoted string has an escaped double quote at the end \""
        "this quoted string has an escaped double quote at the end so it will fail to parse \"
        """)

Please study these examples and see if they give you any insights into how your script is behaving.

**Comment by yldiscover** [comment]
<code>
import os,sys,time,re
import pprint

from pyparsing import *

string_ = quotedString

def p( x ):
      sexpr = string_.parseString( x )
      print repr(x)
      pprint.pprint( sexpr.asList() )

#x = """
#"abc\"
#"""

x = open("1.t").readline()
#Now x = "abc\t" ,which is saved in 1.t
p( x )

</code>

**Comment by ptmcg** [comment]
`quotedString` is designed to accept `\` as an escape character, so that `"this string has \" an embedded quote"` will parse as a quoted string.  `"string with '\' at the end \"` is not a legal quoted string because what looks like a terminating `"` is escaped by the `\`.  So `quotedString` will not parse `"abc\"` as a quoted string.

pyparsing has a `QuotedString` class where you can define your own quoted strings with your own custom escaping rules. It will allow you to define `\` as an escape character, but the default is no escape character. So if you must accept `"abc\"` as a valid quoted string, then use `QuotedString('"')`. Note however, that this will not match `"quoted string with escaped \" quote character"` because the internal `"` will be interpreted as the terminating quote character.

If you want to match *all* the cases in your original question, then you will need something like `quotedString ^ QuotedString('"') ^ QuotedString("'")`.  I don't really think this is a good idea, as it seems like a very ambiguous parser, but that probably answers your question.

**Comment by yldiscover** [comment]
This is a good solution:)
