### ISSUE TITLE
Strange effect of WordStart - Optional(x) - WordEnd 

### ISSUE THREAD

**Issue by telemmaite** [pyparsing/pyparsing#250]
**Thank you so much with this library I am really amazed with how complicated parsing it can achieve with little and readable code !**

Well...these days I am hitting my head with the following effect of WordStart -Optional(x) - WordEnd 
What I am after can be seen with this regex `\b[0-9]{2,3}k?\b` but I don`t know how to achieve the same here..
![image](https://user-images.githubusercontent.com/4275711/98704226-141d0200-2385-11eb-80d6-463e0ec96131.png)

If I use the following expression without WordStart/WordEnd I am able to match `52` and `52k`, so `pp.Optional(pp.oneOf("k mt"))` works as expected by me.

**Good**, input `"topic tess 52k 12345678 xcv"`
```python
(pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') & pp.Regex(r"[0-9]{2,3}")("dwt2") + pp.Optional(pp.oneOf("k mt"))).searchString("topic tess 52k 1234567 xcv")

ParseResults([ParseResults(['tess', '52', 'k'], {'dwt_keyword': 'tess', 'dwt2': '52'}), ParseResults(['123'], {'dwt2': '123'}), ParseResults(['456'], {'dwt2': '456'})], {})
```
**Good**, input `"topic tess 52 12345678 xcv"`
```python
(pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') & pp.Regex(r"[0-9]{2,3}")("dwt2") + pp.Optional(pp.oneOf("k mt"))).searchString("topic tess 52 1234567 xcv")

ParseResults([ParseResults(['tess', '52'], {'dwt_keyword': 'tess', 'dwt2': '52'}), ParseResults(['123'], {'dwt2': '123'}), ParseResults(['456'], {'dwt2': '456'})], {})
```

However because I want to match just the `52` or `52k` part and not 123|456, I add WordStart/WordEnd 

**Good**, input `"topic tess 52k 12345678 xcv"`
```python
(pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') & (pp.WordStart() + pp.Regex(r"[0-9]{2,3}")("dwt2") + pp.Optional(pp.oneOf("k mt")) + pp.WordEnd())).searchString("topic tess 52k 678 xcv")

ParseResults([ParseResults(['tess', '52', 'k'], {'dwt_keyword': 'tess', 'dwt2': '52'})], {})
```

**Bad**, input `"topic tess 52 12345678 xcv"`
```python
(pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') & (pp.WordStart() + pp.Regex(r"[0-9]{2,3}")("dwt2") + pp.Optional(pp.oneOf("k mt")) + pp.WordEnd())).searchString("topic tess 52 678 xcv")

ParseResults([], {})
```

Would gladly appreciate your help.

**Comment by ptmcg** [comment]
Glad to hear you are enjoying using pyparsing!

I had a little trouble following your post, I think your parsers will be more maintainable if you don't crunch everything onto a single line.  For my own sanity I reformatted your issue with some shorter lines, removed repeated definitions of the parsers, and commented out your text so I could run your issue as straight Python.

```
import pyparsing as pp

#~ Well...these days I am hitting my head with the following effect of 
#~ WordStart -Optional(x) - WordEnd

#~ If I use the following expression without WordStart/WordEnd I am 
#~ able to match 52 and 52k, so pp.Optional(pp.oneOf("k mt")) works 
#~ as expected by me.
#~ Good, input "topic tess 52k 12345678 xcv"
parser = (pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') 
          & pp.Regex(r"[0-9]{2,3}")("dwt2") 
          + pp.Optional(pp.oneOf("k mt"))
          )
print(parser.searchString("topic tess 52k 1234567 xcv", maxMatches=1))

#~ Good, input "topic tess 52 12345678 xcv"
print(parser.searchString("topic tess 52 1234567 xcv", maxMatches=1))

#~ However because I want to match just the 52 or 52k part and not 
#~ 123|456, I add WordStart/WordEnd

#~ Good, input "topic tess 52k 12345678 xcv"
parser = (pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') 
          & (pp.WordStart() 
             + pp.Regex(r"[0-9]{2,3}")("dwt2") 
             + pp.Optional(pp.oneOf("k mt"))
             + pp.WordEnd())
          )
print(parser.searchString("topic tess 52k 678 xcv", maxMatches=1))

#~ Bad, input "topic tess 52 12345678 xcv"
print(parser.searchString("topic tess 52 678 xcv", maxMatches=1))

```
With this reformatting, I was able to reproduce your parsing behavior, and also was able to follow your line of thinking!

One of the things which can complicate debugging a parser is using searchString. When you were getting results like:
```
[['tess', '52'], ['123'], ['456']]
```
this was actually 3 separate matches (since your parser will match a lone integer since the `tess` or `dwt` markers are optional, as is the trailing `k` or `mt`). So to troubleshoot this parser, I added `maxMatches=1` to the searchString call.  (searchString *can* be useful for doing isolated expression matching - you just have to be aware that you may get some unintended matches as well.)

The problem with WordEnd in your parser is that, to match the Optional expression, pyparsing is skipping whitespace. When it does not find it, the parse location is already at the beginning of the following word, so WordEnd fails to match.

The solution is to tell the Optional expression to not skip whitespace (which looks like what you want anyway).

```
parser = (pp.Optional(pp.oneOf("tess dwt"))('dwt_keyword') 
          & (pp.WordStart() 
             + pp.Regex(r"[0-9]{2,3}")("dwt2") 
             + pp.Optional(pp.oneOf("k mt")).leaveWhitespace() 
             + pp.WordEnd())
          )
```
By adding leaveWhitespace() to the Optional expression, WordEnd now matches correctly.

You might also take a look at using runTests for trying different input strings for a given parser.

-- Paul

**Comment by telemmaite** [comment]
Thank you a hundred times Paul ! 

You are absolutely right that the code should be properly `un-crunched` sorry for that.
I was also able with a lot of trial and error to come up with  a workaround which now based on your explanation I understand why it works.

I just did a swap like this, no I guess, before Optional eating the `whitespace` it will check and match for WordEnd
```python 
(pp.WordEnd() & pp.Optional(pp.oneOf("k mt"))) 
```
