### ISSUE TITLE
Exclude function names from fnumber in fourFn example

### ISSUE THREAD

**Issue by marvinvanaalst** [pyparsing/pyparsing#265]
Hey guys, 
first of all thanks for the great work! I've come across  the example [fourFn](https://github.com/pyparsing/pyparsing/blob/master/examples/fourFn.py) and noticed that the regex used on line 70 to get numbers from the equation will also match numbers in function names, so e.g. `function_1(a, b)`

```python
fnumber = pp.Regex(r"[+-]?\d+(?:\.\d*)?(?:[eE][+-]?\d+)?")
```

This can be fixed by changing `\d+` to `(?:\d+(?![_\(]))` or possibly something else more readable. Regular expressions are not my strength to be honest.

Below a commented variant of the whole thing, because I really dislike reading regular expressions as a whole 😄
```python
fnumber = pp.Regex(
    r"[+-]?"  # optional plus / minus
    + r"(?:\d+(?![_\(]))"  # digit not followed by _ or (, to exclude function names
    + r"(?:\.\d*)?"  # optional floating point
    + r"(?:[eE][+-]?\d+)?"  # optional scientific notation
)
```
Hope this helps someone, cheers!

**Comment by ptmcg** [comment]
I'm not sure how that function name would accidentally parse the embedded number, since function names are idents, which are parsed using `Word(alphas, alphanums + "_$")`. This would parse the entire function name "function_1" before parsing any numeric values. 

Can you post the expression or string you are parsing that is parsing this way? When I modified four_fn.py to add support for a function named "function_1", there was no problem parsing or evaluating it.

**Comment by marvinvanaalst** [comment]
Now that I checked it again it seems to work with both cases. Maybe I had messed up something in between that I later fixed again. ;)

Thanks, I'll close the issue!
