### ISSUE TITLE
Identify which token caused the parsing error

### ISSUE THREAD

**Issue by numerys** [pyparsing/pyparsing#302]
I have a big grammar like

    grammer = A + B + C + D + ... + Z

When invoked like

    parse  = grammar.parseString(bad_input, parseAll=True)

with an ``bad_ìnput``` I get an exception like

    Expected end of text, found '"'  (at char 1034), (line:6, col:1)

which is expected. What I would like is to have a more detailed exception which is telling me, which "sub-grammar" ```A, B, C, D, ..., Z``` is causing the error.

Could I get such?

**Comment by ptmcg** [comment]
Yes! Pyparsing's default behavior is to just flag the outer expression. But if you want a more localized exception, use a "-" operator instead of "+" in your expression:

    grammar = A - B + C + D + ...

You just need the one, and then all of pyparsing's backtracking after that point is suppressed. (You may be tempted to use "-" instead of "+" throughout your grammar, but this will defeat pyparsing's alternative matching.)

Also, please take a look at using `runTests`:

    grammar.runTests("""\
        a b c d x
        x y z
        """)

This will do a lot of the test setup, looping, exception catching, and results formatting for you.

**Comment by numerys** [comment]
Ahh, thanks. One more difficulty I do have. If more that one grammer exists like

    g0 = A - B + C + D
    g1 = A - B +     D
    grammar = pyparsing.OneOrMore(g0 | g1)

I ran into ```g0``` throwing an exception before ```g1``` got it's chance.

If I do

    g0 = A - B + C + D
    g1 = A + B +     D

it works as expected. Am I on the right track?

**Comment by ptmcg** [comment]
Yes. That's why "-" is not the default behavior.

Look at your grammar and see if there are parts where you can say "After parsing this, then any exception afterword is a real error," then that is a good place to drop in "-". It might not be at this high a level, but at a lower level expression. (I really need to write up the wiki page on this...)

**Comment by numerys** [comment]
Great, thanks
