### ISSUE TITLE
License file missing from the latest source tarball at PyPI

### ISSUE THREAD

**Issue by ocefpaf** [pyparsing/pyparsing#31]
I guess that the directory move in https://github.com/pyparsing/pyparsing/commit/27e183a78c8062ed7c2bbb91655a5e56cd697bba is the cause for that.

**Comment by ptmcg** [comment]
Thanks for the quick checkout of the new release!
A) do you know if there is a way to remedy in-place without pushing a new release? (I am a bit skeptical)
B) if not, is this a critical omission that would require a quick-turn 2.2.2 or 2.2.1.1?
If a new release is required, I will probably wait another day or two to address any other warts that crop up, and then push out a 2.2.1.1. This is the first release since moving to GitHub, so I'm not totally surprised that there are some hiccups. I just hope they are all this simple.

**Comment by ocefpaf** [comment]
> A) do you know if there is a way to remedy in-place without pushing a new release? (I am a bit skeptical)

You can do a post release but that is kind of a new release :smile: 

> B) if not, is this a critical omission that would require a quick-turn 2.2.2 or 2.2.1.1?

Not critical as long as it is acknowledge here that the file was missing so packagers downstream are not blamed for infringing the license terms.

 IMO we can wait a normal release cycle to fix this.

**Comment by ptmcg** [comment]
So acknowledged.

Now that I have made the leap to releasing from GH, I hope I can do these more often than every 18 months now!

Thanks again!

**Comment by ocefpaf** [comment]
Thanks for the quick response!
