### ISSUE TITLE
Regression in 3.0.2, 3.0.3, and 3.0.4

### ISSUE THREAD

**Issue by nijel** [pyparsing/pyparsing#323]
In [translate-toolkit](https://github.com/translate/translate/) we use pyparsing for [parsing Windows RC files](https://github.com/translate/translate/blob/master/translate/storage/rc.py).

I did port the code to 3.0.1 and everything worked fine. On 3.0.2 and 3.0.3 we get testsuite failures (see https://github.com/translate/translate/runs/4028529279?check_suite_focus=true).

The guilty commit is https://github.com/pyparsing/pyparsing/commit/4ab17bb55d1ba72adef66c01232711d421650767, reverting it makes it work again.

**Comment by nijel** [comment]
I was also not able to extract smaller testcase so far, but here is my observation so far:

* The difference is in `transform_string` result - with 3.0.1 it includes leading `\r\n` in 3.0.2-3.0.4 it is ommitted 
* The actual problematic code are following two lines, commenting them out fixes our tests:

https://github.com/pyparsing/pyparsing/blob/e269b0a3d067e66ef718b8508a4a82927c7606d0/pyparsing/core.py#L3850
https://github.com/pyparsing/pyparsing/blob/e269b0a3d067e66ef718b8508a4a82927c7606d0/pyparsing/core.py#L3859

**Comment by ptmcg** [comment]
Without being able to reproduce the problem or test case, we are stuck with trial and error. If I remove those lines, other pyparsing tests fail.

Can you restore those lines, but instead delete these lines in `Or.parseImpl`, and then rerun your tests?

        if all(e.callPreparse for e in self.exprs):
            loc = self.preParse(instring, loc)

https://github.com/pyparsing/pyparsing/blob/master/pyparsing/core.py#L3869-L3870

**Comment by nijel** [comment]
Okay, here is the reproducer:

```python
from pyparsing import Keyword, Word, alphanums, alphas

block_start = (Keyword("{") | Keyword("BEGIN")).set_name("block_start")
block_end = (Keyword("}") | Keyword("END")).set_name("block_end")

reserved_words = block_start | block_end

name_id = ~reserved_words + Word(alphas, alphanums + "_").set_name("name_id")

dialog = name_id("block_id") + (Keyword("DIALOGEX") | Keyword("DIALOG"))("block_type")

string_table = Keyword("STRINGTABLE")("block_type")

parser = dialog ^ string_table

parser.addParseAction(lambda x: x)
result = parser.transformString(
    b"""\r\nSTRINGTABLE\r\nBEGIN\r\n// Comment\r\nIDS_1 "Copied"\r\nEND\r\n""".decode()
)
print(repr(result))
assert result[:2] == "\r\n"
```

The change you have suggested in `Or.parseImpl` has no effect here.

**Comment by ptmcg** [comment]
This is a huge help, and reproduces the problem nicely, thanks!

**Comment by nijel** [comment]
It can be probably simplified even more, I just didn't have time to play with it further. Maybe following parser will be enough to trigger this as well:

```py
parser = ~Keyword("BEGIN") ^ Keyword("STRINGTABLE")
```

**Comment by ptmcg** [comment]
Yep. Even this triggers it:

    ~Empty() | Empty()

The '~' (generates a `NotAny` expression), as part of an Or or MatchFirst, triggers the problem.  So I have a pretty minimal repro test case to work with now, but I'll also validate against your more complete example once I have a possible fix.

**Comment by ptmcg** [comment]
Ok, I've come up with a fix, BUT it is a change in `NotAny` that makes me a little anxious. The change passes all my unit tests, but as we have seen in the past week or so, there are many more parser cases out there than are covered by my test suite. So I am a little reluctant to stir things up again. This is the kind of API change that should really go through the pre-release phases.

However, I think I have found a workaround in your parser, that works with the current released version (and should work with all the versions, I think).  Replace:

    name_id = ~reserved_words + Word(alphas, alphanums + "_").set_name("name_id")

with

    name_id = Combine(~reserved_words + Word(alphas, alphanums + "_")).set_name("name_id")

Please give this a try.

Otherwise, I would ask you to pin your pyparsing version to an existing version that works for you, until I can introduce this other change in a 3.1.0 pre-release.

**Comment by nijel** [comment]
The workaround with `Combine` doesn't work (or at least not with other changes) - it then seems to parse only first letter instead of whole word. It might be a bug in our parser as well, TBH my knowledge of this code is quite limited...

**Comment by ptmcg** [comment]
<sigh> ok. I won't be able to look at this again for a few days now, so for now you should probably pin to 2.4.7. I would not recommend pinning to 3.0.1, it is broken in some other areas.  I'll leave this open so I can revisit - hopefully this weekend.

**Comment by nijel** [comment]
I've already ported the code to 3 API, so pinning to 2.4.7 would need reverting these changes. We will stick with 3.0.1 for now as it works fine in the test suite and I believe it covers most of the use cases.

**Comment by ptmcg** [comment]
I have a modified version of `rc.py` and `po2rc.py` that work with pyparsing 3.0.5 (in the attached zip file). I think that there are some issues with the way the negative lookahead created with the `~` operator (generating a `NotAny`) has changed when used in `transform_string`. I've reworked the rc grammar to move the negative lookahead into the corresponding `ZeroOrMore` constructs, where it is behaving correctly now.
[modified_rc_files.zip](https://github.com/pyparsing/pyparsing/files/7494183/modified_rc_files.zip)

**Comment by nijel** [comment]
Thanks, that makes sense. I've turnet it into https://github.com/translate/translate/pull/4468

**Comment by ptmcg** [comment]
Can this issue be closed now?

**Comment by nijel** [comment]
For translate-toolkit it is fixed. It's up to you if you consider this big in pyparsing or in our parser

**Comment by ptmcg** [comment]
The negative lookahead works in pyparsing for normal calls to `parse_string`, but is inherently invalid to use in `scan_string` or its two related methods `transform_string` and `search_string` (which are just thin wrappers around `scan_string`). Say you have a grammar to parse identifiers, that don't start with keywords, and `input` and `print` are keywords. 

    text = "input x y print x y"

    keyword = one_of("print input", as_keyword=True)
    identifier = ~keyword + Word(alphas, alphanums)

`parse_string` does what we want

    result = (keyword + Group(ZeroOrMore(identifier))).parse_string(text)
    print(result)

    ['input', ['x', 'y']]

But not so with `scan_string`. Scanning a character at a time will not match 'input', but will match 'nput'

    print(identifier.search_string(text))

    [['nput'], ['x'], ['y'], ['rint'], ['x'], ['y']]

Upcase identifiers will upcase more than we want:

    identifier.add_parse_action(pyparsing_common.upcase_tokens)
    print(identifier.transform_string(text))

    iNPUTXY pRINTXY

Making our transformer recognize keywords, but not transform them is one solution.

    identifier = Word(alphas, alphanums)
    identifier.add_parse_action(pyparsing_common.upcase_tokens)
    transformer = keyword | identifier
    print(transformer.transform_string(text))

    input X Y print X Y

Adding WordStart before the negative lookahead is another.

    identifier = WordStart() + ~keyword + Word(alphas, alphanums)
    print(identifier.search_string(text))
    identifier.add_parse_action(pyparsing_common.upcase_tokens)
    print(identifier.transform_string(text))

    [['x'], ['y'], ['x'], ['y']]
    input X Y print X Y

With this simple parser, I couldn't come up with an easy example using the `stop_on` approach that I sent you earlier. After making this write-up, I think adding `WordStart()` before the negative lookahead might actually be the cleaner solution.

And lastly, why did this work in 2.4.7 but break in 3.0? I think it goes back to how whitespace skipping was changed for the `ParseExpression` subclasses `Or` and `MatchFirst`, so that these expressions would not implicitly override `leaveWhitespace()` that might be defined in one of their alternative sub-expressions.

So for `pyparsing`, I'd say it's not so much a bug as a limitation - if anything, the bug is that it is not documented better.  I'll probably lift much of this comment into a wiki page or blog post to try to address that.

**Comment by nijel** [comment]
Documenting this is certainly a good approach.

**Comment by ptmcg** [comment]
Documented in the Common Pitfalls wiki page:
https://github.com/pyparsing/pyparsing/wiki/Common-Pitfalls-When-Writing-Parsers#using-scan_string-with-an-expression-using-negative-lookahead--operator
