### ISSUE TITLE
Potential Bug ?

### ISSUE THREAD

**Issue by PosoSAgapo** [pyparsing/pyparsing#368]
Hi, I have tried the following code to parse this string:
```
from pyparsing import nestedExpr  
test =  "( dist ( query ( around ( center ( area ( keyval ( ' name ' , ' Edinburgh ' ) ) , nwr ( keyval ( ' name ' , ' Mary King ' s Close ' ) ) ) , search ( nwr ( keyval ( ' shop ' , ' bakery ' ) ) ) , maxdist ( DIST_INTOWN ) ) , qtype ( latlong ( topx ( 1 ) ) ) ) , for ( ' car ' ) ) )"  
data =  nestedExpr('(', ')').parseString(test).asList() 
```
it gives the following error,`pyparsing.exceptions.ParseException: Expected ')', found '('  (at char 7), (line:1, col:8)`, but I  don't see any ')' at char 7, is this a bug or did I use a wrong parser? As I try to remove brackets one by one and I found the problem is caused by `' s` in `Mary King ' s Close`, removing the `'` in the `' s` will make this parsing back to normal, but I only use `(` and `)` as the target of the parser, the `' s` is not supposed to have any influence on the parsing, is this a feature or a bug?

**Comment by ptmcg** [comment]
At first, I figured this was an issue of mismatched "(", ")"s, so I ran this code (btw, I strongly encourage using runTests to help identify parser issues):

```
# '(' and ')' are the default opener and closer for nestedExpr
parser = nestedExpr()

parser.runTests([
    test + "))))))))"
])
```

At which runTests reports just how many ")"s are too many to add to the end.

So this code parses:

```
parser.runTests([
    test + "))))"
])
```

I then read further in your issue, that you could parse successfully if you remove `'` characters. `nestedExpr's` default behavior is to detect quoted strings and ignore opener/closers that are in quotes. So that "(name ('Bob (short for Robert)'))" parses as `[['name', ["'Bob (short for Robert)'"]]]` not `[['name', ["'Bob", ['short', 'for', 'Robert'], "'"]]]`. Looking closer at your test string, there is this portion:

```
keyval ( ' name ' , ' Mary King ' s Close ' )
```

Which looks like it is actually trying to parse the name "Mary King's Close". But since you are using `'` for your quote characters, the `'` in the name is accidentally closing the quoted string, which then throws off all the quote matching, and starts treating ")"s as being inside quotes, and so they are ignored.

If I change to 

```
keyval ( ' name ' , ' Mary Kings Close ' )
```

or

```
keyval ( ' name ' , " Mary King's Close " )
```

your parser works.

You can also see how this behaves if you pass the optional `ignoreExpr` argument to `nestedExpr` as `nestedExpr(ignoreExpr=None)`.  The default `ignoreExpr` is pyparsing's `quotedString`.

**Comment by PosoSAgapo** [comment]
Thank you for your detailed explanation,  so if I want to ignore the `quotedString` feature, I just replace it with `None`, then the code could behave like what I intended to do, eg not parsing `'`, only parsing `(` and `)` ?  I do not pyparsing have this feature, sorry for my misreport.

**Comment by ptmcg** [comment]
Yes. In place of `nestedExpr('(', ')')`, use `nestedExpr('(', ')', ignoreExpr=None)`, or just `nestedExpr(ignoreExpr=None)`, since "(", ")" are the default opener/closer strings.
