### ISSUE TITLE
Opt() is not associative

### ISSUE THREAD

**Issue by Reilman79** [pyparsing/pyparsing#389]
I'm working on writing my first parser using pyparsing and ran into an interesting case regarding the `Opt()` class that resulted in an error. It appears that the `Opt()` class is not associative `i.e. (Opt(A) | Opt(B)) != Opt(A | B)`. To me, this does not seem like the desired behavior, but if it is I'd like to know why it behaves this way. I'll walk through a pyparsing specific example.

```
from pyparsing import *

TEST, WORD, OTHER = map(CaselessKeyword, "TEST WORD OTHER".split())

keyword = MatchFirst((TEST, WORD, OTHER))

clause_1 = Opt(TEST) | Opt(WORD) | Opt(OTHER)

clause_2 = Opt(TEST | WORD | OTHER)

clause_3 = Opt(WORD) | Opt(TEST) | Opt(OTHER)

clause_4 = Opt(TEST) | WORD | OTHER

grammar = clause + StringEnd()

results = grammar.parse_string("WORD")
print(results.as_list())
```

Here I've defined a very simple parser that consists of a few keywords and a few clauses created from those keywords, the `MatchFirst` operator, and the `Opt()` class. Then, grammar is just defined as a clause plus the end of the string; I've left clause un-numerated here to show it can represent either of the four defined clauses. Each clause represents a different case so I'll go through each one below. 

For each of the four clauses the string we are attempting to parse is simply the word `"WORD"`.

#### clause_1
Let's say that `grammar = clause_1 + StringEnd()`. When running the file I would expect it to parse `"WORD"` to the keyword of the same name, given that it is an option in the `MatchFirst` statement. However, instead it results in the following error:
`pyparsing.exceptions.ParseException: Expected string_end, found 'WORD'  (at char 0), (line:1, col:1)`.

#### clause_2 
Now let's say that `grammar = clause_2 + StringEnd()`. Again I would expect the string to parse to the `WORD` keyword. In this case it actually does so and we get the desire output: `['WORD']`.

#### clause_3
Now let's say that `grammar = clause_3 + StringEnd()`. `Clause_3` is weird because it is the same as `clause_1`, except now the item we expect to match appears first in the `MatchFirst` statement. Just like in `clause_1`, I would expect this to parse the correct keyword; however, unlike in `clause_1`, it actually does. Running this, I received no errors and the desired output: `['WORD']`.

#### clause_4
Finally, let's say that `grammar = clause_4 + StringEnd()`. `Clause_4` is again the same as `clause_1`, except now only the first keyword `TEST` is optional. In this case, I thought perhaps it would be able to parse to the proper keyword, since it is provided as a required item to the `MatchFirst` statement. However, this still results in the same error seen with `clause_1`:
`pyparsing.exceptions.ParseException: Expected string_end, found 'WORD'  (at char 0), (line:1, col:1)`.

Based on these results, it seems that when an `Opt()` case appears in a `MatchFirst` statement then the rest of the statement is disregarded. Is this the desired behavior? Either way I would be interested to know why this behavior occurs. Thanks!

**Comment by ptmcg** [comment]
Actually, I think you are thinking of the distributive property (where `a*(b+c)` equals `a*b + a*c`). And no, Opt is not distributive over '|', which is not commutative either. `|` *is* associative, in that `A | B | C` is equivalent to `(A | B) | C` and `A | (B | C)`.

`Opt(expr)` is equivalent to `expr | ε` where `ε` is an empty match - note that `ε` ALWAYS matches. So `Opt(A) | Opt(B)` is equivalent to `A | ε | B | ε`.  If the first element in the list is not a match for `A`, then the next test is `ε`, and so matches and yields an empty string. Since your test code assumes that the grammar is followed by StringEnd(), an error gets raised, because after matching null, the parser is still positioned at the W in WORD, and so you get your error message.

You may get better results if you use the '^' operator, which *is* (mostly) commutative.  Try:

    clause_5 = Opt(TEST) ^ Opt(WORD) ^ Opt(OTHER)

Unlike '|', which immediately returns after its first successful match (which is '' if the input string isn't "TEST"), '^' evaluates _all_ the alternatives, and returns the longest match.

(I say that "^" is mostly commutative because if A and B both match the same length input, then A ^ B will match A, but B ^ A will match B, so strictly speaking not equivalent.)

**Comment by Reilman79** [comment]
Whoops, my bad on the property name. It is the distributive property I was describing, don't know why I was thinking associative.

Thank you for this excellent explanation. I didn't realize Opt(expr) was a direct swap for the `expre \ ε`. I thought it probably was related to how the parser read it behind the scenes, but this makes a lot of sense.

As far as the errors, I actually added the StringEnd() to force an error so I would know it was failing in the scenario. In my own parser, I've already made the fix but was interested to see why this worked this way. But I appreciate the feedback here.

Thanks again, closing issue.
