### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by douloveppt** [pyparsing/pyparsing#394]
```python
text = """
    localhost.localdomain. {
        bbb {
            sss {
                qwe [123 sdf 3];
            }
            ww qwe;
            fff {
                kkk we;            
            }
            ggg [sd f ff];
        }
    }
"""

data_word = Word(alphanums + "-/._")
label = data_word + Suppress(White())
_list = Literal("[").suppress() + Group(OneOrMore(data_word)) + Literal("]").suppress()
# attr_expr = (label + Suppress(White()) + OneOrMore(data_word, stop_on=label).set_parse_action(' '.join) + Suppress(";"))
attr_expr = label + Or([ZeroOrMore(data_word).set_parse_action(' '.join), _list]) + Suppress(";")

_in = Forward()
block = label + Literal("{").suppress() + Each(Dict(ZeroOrMore(Group(attr_expr))) + _in) + Literal("}").suppress()
# print(OneOrMore(attr_expr).parse_string(text).dump())
_in <<= Dict(ZeroOrMore(Group(block)))
result = Dict(OneOrMore(Group(block))).parse_string(text)
# print(result.dump())
print(result.as_dict())
```

```
Traceback (most recent call last):
  File "/Users/bibowang/Documents/workspace/demo/test2.py", line 154, in <module>
    result = Dict(OneOrMore(Group(block))).parse_string(text)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected '}', found 'bbb'  (at char 38), (line:3, col:9)
```

**Comment by douloveppt** [comment]
thanks, 期待您答复！！！（your friend from china）

**Comment by ptmcg** [comment]
This part of your input is the part that your parser is choking on:

            sss {
                qwe [123 sdf 3];
            }

so review that part of your parser to see if it can be fixed up.

In general:
- Try stepping back and writing a BNF for this format, and just think in parser patterns, not pyparsing classes. Test your BNF against different structures. THEN implement using pyparsing.
- Don't parse for White() explicitly - let pyparsing take care of the whitespace skipping.
- Use runTests to do your testing, and instead of writing one complex test, write a series of tests that add more and more features. That way if your parser stumbles over a simple construct, you will be able to identify it more quickly.
- If really struggling, use setName() and setDebug() to get pyparsing to print out its progress through your parser. This is pretty low-level though, so I would try the other steps first.

**Comment by douloveppt** [comment]
> 

Thanks for your reply, I'm learning how to use this library and it helps me a lot, thanks again.
