### ISSUE TITLE
When OneOrMore(Regex()), the program will be stuck.

### ISSUE THREAD

**Issue by douloveppt** [pyparsing/pyparsing#395]
I want to match Chinese
my code like this:
```python
from pyparsing import *

s = r"sdf你好 123 "

data_word = OneOrMore(Regex(r"[a-zA-Z0-9 \u4e00-\u9fa5-/._]*"))

result = data_word.parse_string(s)
print(result)
```
When I run the program it freezes...
(version: 3.0.7)

**Comment by ptmcg** [comment]
It runs forever because your regex will match the empty string, so when it reaches the end of s, it will continue to match forever.

Try this, change your code to this:

    data_word = Regex(r"[a-zA-Z0-9 \u4e00-\u9fa5-/._]*")
    data_word.set_name("data_word")
    data_word.set_debug()
    
    result = data_word[...].parse_string(s)
    
    print(result)

To see how the "*" matches forever at the end of the string. Then change the last character in your regex to "+" and rerun to see the difference.

Also, try removing the " " in your regex after "0-9", and see how things change.

**Comment by ptmcg** [comment]
Also, I'm happy to hear you are using pyparsing to parse Chinese. Would you mind trying out the Chinese language set in the pyparsing.unicode.Chinese namespace class? There are alphas, nums, printables, etc. defined for you in place of "\u4e00-\u9fa6" type character ranges.

**Comment by douloveppt** [comment]
> Also, I'm happy to hear you are using pyparsing to parse Chinese. Would you mind trying out the Chinese language set in the pyparsing.unicode.Chinese namespace class? There are alphas, nums, printables, etc. defined for you in place of "\u4e00-\u9fa6" type character ranges.

thank you, I'll try it.
