### ISSUE TITLE
Having items on same parse level in infix_notation with differing op's and opAssoc's

### ISSUE THREAD

**Issue by Vlek** [pyparsing/pyparsing#398]
I have made [a dice roller that relies heavily on Pyparsing](https://github.com/Vlek/roll-cli). I am currently running into an issue where [I have multiple notations that are mostly similar that are currently set as different levels that are causing the recursion test to exception](https://github.com/Vlek/roll-cli/blob/main/src/roll_cli/parser/diceparser.py#L128).

The main reason I cannot add them all together using an OR is because they include ops either to the left and/or right. My notation for d% expects an optional number to the right, but my normal dice roll notation expects at least a right-hand number but also will accept a left-hand one.

My question is, I am fairly certain I am using this wrong, so how should I instead be using Pyparsing in this case? Am I able to salvage the infix_notation to continue using it or do I have to do it by hand instead? I believe that I can use the Optional method to construct something that will remove at least the issue with dice rolling, but I would want all six different dice-specific parsing portions to be on the same level, something that I believed I would have to use `|` to do.

**Comment by ptmcg** [comment]
I did a very similar thing to this writing a dice roller with pyparsing to parse the terms, along with math etc., so I know just what you mean about using "d" as both a unary and binary operator.

When I wrote my parser, I made the binary "d" operator left-associative. Your code makes it right associative (https://github.com/Vlek/roll-cli/blob/main/src/roll_cli/parser/diceparser.py#L125). Changing this might be all you need to fix this. 

(I see you also have unary/binary operators "k" and "x", where unary and binary are both left-associative - you might want to make the unary versions right-associative.)

I'm not super keen on how you have unary minus at multiple levels, you should be able to just use one, and if the precedence isn't to your liking (like "-2**4" giving -16), then document that it needs to be "(-2)**4". (For comparison, Python evaluates "-2**4" as -16.)

Having operators "d%" and "d" might cause some issues with the parsing. I had this with adding "!" for factorial and "!=" for not equal. I had to define the factorial operator with a negative lookahead (`~Literal("!=") + "!"`) to keep the parser from getting lost.

I wrote a pyparsing wrapper package called [plusminus](https://github.com/pyparsing/plusminus) to simplify writing domain-specific arithmetic libraries, and a dice roller is one of the examples. Give it a look for ideas you might want to add to your project. plusminus includes guards against hostile input (like "9**9**9"), and does some work to try to reduce floating-point precision surprises (like "1/49 * 49 == 1" which Python evaluates as False since it does direct floating point '==', but plusminus uses `math.isclose` for floating point comparisons and so reports True). There is a public web page you can try out with plusminus at http://ptmcg.pythonanywhere.com/plusminus . (I should probably make another page of that with the plusminus dice roller parser.)

**Comment by Vlek** [comment]
@ptmcg, thank you for responding.

- left-association: I don't think that this matters when you have two opts. I have tried both ways just to be sure that this didn't solve my recursive issue and it did not appear to do so. I believe that this is important when you have a unary operator. In my case, I have things like `d%` which is a shorthand for `1d100`. In this case, the addition would be in the front to signify that more than one d100 ought to be rolled.

- I will also as you said have to apply whatever fix I use for the standard `d` dice roll to the x and k operators.

- The unary minus at multiple levels is because of some tests that I have that fail when I do not have it like that. I know it's wonky and it's probably not right, but for some reason, it is working for me right now and I am very afraid to change it.

- The lookahead is OK because I believe I should be using [Keyword](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#basic-parserelement-subclasses) for that anyway which should resolve the issue of `d` being seen in `d%` if it comes up. I have fortunately not run into this issue I do not believe but may apply that change anyway just to be safe.

- I will take a look at your package, thank you.

**Comment by ptmcg** [comment]
Not sure I was clear in my left/right recommendation. The unary 'd' should be right-associative, and the binary 'd' should be left-associative.

I also did a very rough web page for a dice roller (which would probably be much easier to write using PyScript). http://ptmcg.pythonanywhere.com/dice_roll

**Comment by ptmcg** [comment]
We haven't discussed this in a while, let me reiterate my last note, but I'll close this issue soon:

    d100 - d is a right-associative unary operator, to implement a single 100-sided die
    3d100 - d is a left-associative binary operator, to implement 3 separate 100-sided dice

In your repo, [this line](https://github.com/Vlek/roll-cli/blob/d362da3ba1068725e62791476e5ad117062f88ba/src/roll_cli/parser/diceparser.py#L125) should say opAssoc.LEFT.

Looking at your code, I see you also have a `d%` operator - you may have to write the 'd' operators as `~Literal("d%") + "d"` or `Literal("d") + ~FollowedBy("%")` so has to keep from matching a `d` operator when encountering `d%`.

**Comment by ptmcg** [comment]
Once again, I'm sorry for not being clear. My second statement was not intended to *combine* the d% and d operators, it was to make the two d operators certain to not be mistaken for the first 'd' of a 'd%' operator. I've had that issue with confusing '!' (for factorial) with '!=' (for not equal), and had to insert a similar guard for the factorial operator.

Just glancing at your code, I see you also have a '%' operator for modulo. Is it possible that that operator could also be confounding some of your parser?

I did clone your repo and use the `create_diagram` function to create a railroad diagram for your parser. The only thing that strikes me a odd is that your atom expression includes "d%", which will probably conflict with your 'd%' operator. Also, the diagram probably has a flaw in that only one of the +/- terms shows up, since the diagram code assumes all subdiagrams will have unique names. 

Try paring back your `infix_notation` operations to just +/-, the unary and binary 'd' operators and get that working. Then add the unary and binary 'd%' operators, and get that working. Then start adding other operations one at a time. Let me know if you want help using the create_diagram method to assist in your troubleshooting.

Otherwise, I'm running out of ideas.
![screencapture-localhost-63342-roll-cli-dice-parser-html-2022-07-11-21_18_52](https://user-images.githubusercontent.com/383875/178395977-12e7e6e0-0a7a-40d4-9388-6371b33e69cb.png)

**Comment by ptmcg** [comment]
Closing this issue, feel free to reopen if you want to revisit.
