### ISSUE TITLE
Pyparsin Opt not working.

### ISSUE THREAD

**Issue by thatrandomperson5** [pyparsing/pyparsing#448]
I have the following:
```py
nameblock = Group(
     name("name") + Suppress(Char(":")) + Opt(name) + suite
).set_parse_action(toContainer)
```
And when I add the `+ Opt(name)` part it instantly thinks it is required and stops parsing normally.

**Comment by ptmcg** [comment]
Here is the code I wrote to try to fill in some blanks and reproduce this issue:

```python
# https://github.com/pyparsing/pyparsing/issues/448
from pyparsing import *

name = Word(alphas)

# do this for better debugging
# name = Word(alphas).set_name("name").set_debug()

suite = nested_expr("{", "}")


def toContainer(t):
    return {t.name: t[-1]}


nameblock = Group(
     name("name") + Suppress(Char(":")) + Opt(name) + suite
).set_parse_action(toContainer)


nameblock.run_tests(
    """\
    abc: {d e f}
    ghi: {k l {m n }}
    pqr: namex {s t {u v}}
    """
)
```

Everything parses properly, both with and without the name after the colon.

You might want try enabling the debugging code on your name expression to see what is going wrong with your parser. It is possible that the input text does not match the name expression (in my first pass at writing this code, I used "name_2", which failed because it does not match the Word(alphas) definition - easy mistake to make).

If there is more to this, you may have to post a bit more of your parser, plus the input text that triggers the problem.

**Comment by thatrandomperson5** [comment]
Thanks for your response. This is a minmal reproducible example
```py

from pyparsing import *
import json
def make_parser():
    name = Word(alphanums+"_")
    iconstruct = Word(alphas)("string") | Word(nums)("int")
    struct = Forward()
    suite = IndentedBlock(struct)
    nameblock = Group(
            name("name") + Suppress(Char(":")) + Opt(name) + suite
    )
    struct <<  Group(nameblock | iconstruct)
    block = OneOrMore(struct)
    return block

parser = make_parser()
out = parser.parseFile("test.txt").asList()
with open("results.json", "w") as r:
    json.dump(out, r, indent=2)

```
test.txt
```

Hello:
   yooo
Helloeeoeoe:
  49392919
Obj:
    item:
       5
    item2:
       hello

```
The optional “name” seems to be cutting off a-lot of the results.

**Comment by ptmcg** [comment]
Ok, the issue is that when you add in the `Opt(name)`, after parsing "Obj", pyparsing thinks "item" is the optional name, which then fails when it hits the ":".

Solve this by changing `nameblock` to:

    nameblock = Group(
            name("name") + Suppress(Char(":")) + Opt(name + ~FollowedBy(":")) + suite
    )

**Comment by thatrandomperson5** [comment]
Closing for now, I abandoned the project. If I ever come back and need it I’ll Re-open
