### ISSUE TITLE
ZeroOrMore can only handle one URL

### ISSUE THREAD

**Issue by dave-kennedy** [pyparsing/pyparsing#459]
Python 3.10, pyparsing 3.0.9:

```
print(pp.common.url[...].parse_string('http://foo.com'))
# ['http://foo.com']

print(pp.common.url[...].parse_string('http://bar.com'))
# ['http://bar.com']

print(pp.common.url[...].parse_string('http://foo.com http://bar.com'))
# []
```

**Comment by ptmcg** [comment]
Good catch, this should have been obvious when adding it. The regex for url ends with '$', so parsing multiple urls should be possible _if_ they are on separate lines.

I'll remove the terminating '$' for the next release. Thanks for pointing this out!

**Comment by ptmcg** [comment]
It turns out that the leading '^' was also a problem.

There are issues with embedding url in larger expressions. For instance, `delimited_list(url)` for a comma-separated list of URLs will require a space before delimited commas (since the ',' character is valid as part of the URL expression). But for your case, where the URLs are just space-delimited, the new URL works fine.

As a workaround, you can define your own url expression as:

    url = pp.Regex(pp.common.url.reString.removeprefix('^').removesuffix('$'))

If you are on Python 3.8 or earlier, use:

    url = pp.Regex(pp.common.url.reString.lstrip('^').rstrip('$'))

**Comment by dave-kennedy** [comment]
Amazing. Thanks for the awesome lib!
