### ISSUE TITLE
using a config file instead of inline pattern

### ISSUE THREAD

**Issue by yosiasz** [pyparsing/pyparsing#473]
Greetings!

thanks so much for this
!
Hoping to use a config file so that the patterns are not done inline but based on a config file you can call as

```
python xlog.py sample.log --config.file=config.yaml
```

Would that be possible so that the python script stays vanilla?

Gracias!

**Comment by ptmcg** [comment]
You would need to represent the grammar in the yaml as a string, instead of as Python statements. You *could* store the grammar as a string that the script evaluates using "eval". You could use pickle with the old version 0 protocol to convert a grammar into a string that could be unpickled (this is really only a small step away from using eval).

You could store the grammar as EBNF, and use the EBNF->pyparsing conversion in the ebnf parsing example - I think this last one is closest to what you would want.

**Comment by ptmcg** [comment]
Is there more to this question? If not please close it.
