### ISSUE TITLE
Consider rewriting slow parts in rust

### ISSUE THREAD

**Issue by jonathan-s** [pyparsing/pyparsing#490]
I have program that runs the function `parse_string` from pyparsing 402 times, and the cumulative time this takes is 1.242s. It would most definitely speed up this library if slow parts were outsourced into rust.

**Comment by ptmcg** [comment]
There is a cPyparsing project that was built by Evan Hubinger that he used for his coconut language parser. It uses cython to speed up the parsing process.

**Comment by ptmcg** [comment]
Have you tried enabling packrat parsing? This is especially helpful if you include an infix_notation expression as part of your parser.

Here is a wiki page with more performance suggestions: https://github.com/pyparsing/pyparsing/wiki/Performance-Tips

**Comment by jonathan-s** [comment]
Thanks! I'll explore this and see if it makes a difference!

**Comment by ptmcg** [comment]
Any further notes on this?

One of the core dev goals for pyparsing is to maintain pure Python-ness, so that it is easy to install in any Python-compatible environment. So actually using Rust or C or other speed up is not consistent with that. Also, pyparsing's internal implementation using Python exceptions to signal parsing success/failure is really where most of the performance time goes.

I'll take a look at what Evan Hubinger has done with cPyparsing to see where using Cython has sped things up, and see if that gives me any ideas on pure-Python options.

**Comment by ptmcg** [comment]
I've looked over the optimizations in cpyparsing, some have already been added into pyparsing, and some are quite extensive/invasive and beyond just casual inspection. I _am_ looking into learning Rust (at this [excellent website](https://tomshlomo.github.io/rust-with-via/index.html)) for some personal projects, and if I find a way to boost performance while still meeting these other dev goals, I'll be sure to add it to pyparsing.
