### ISSUE TITLE
quoted_string railroad diagram differs when multiple

### ISSUE THREAD

**Issue by RoDuth** [pyparsing/pyparsing#528]
I've been updating the parser for an old project recently and can I say the railroad diagrams are a great feature!

I found an anomaly when using quoted_string in multiple places with set_result_name.

When used in a single place I get:
<img width="574" alt="image" src="https://github.com/pyparsing/pyparsing/assets/15710055/42adaed1-d148-472d-bdb9-b1ad9819a474">

but when used in multiple places, e.g.:
```python
from pyparsing import *


quoted_string.set_parse_action(remove_quotes)
none_token = Keyword("None")
numeric_token = Regex(r"[-]?\d+(\.\d*)?([eE]\d+)?").set_name("numeric token")
value_token = (none_token | quoted_string).set_name("value")("value")
date_value_token = (numeric_token | quoted_string).set_name("date value")("value")
generic_token = (date_value_token | value_token).set_name("generic token")
generic_token.create_diagram("test.html")
```
I get:
<img width="549" alt="image" src="https://github.com/pyparsing/pyparsing/assets/15710055/5f2c4727-68c7-479b-9bf5-75ac964c077b">

I did try `.copy()` and a few other ideas but none of them made any difference.

**Comment by ptmcg** [comment]
Yes, there is a known problem with the railroad diagrams generating empty blocks, that I've tried a few times to chase down, but it eludes me. That feels like a separate problem from this one, and I think I opened an issue on it a while ago, but closed it when I thought I had it fixed - turns out my solution was only a partial one. I'll reopen that ticket or create a new one.

It's possible that the multiple instances are actually creating separate expression copies (which is what happens internally when setting results names), and this might be part of the issue that I didn't consider before.

**Comment by RoDuth** [comment]
Sorry for an extremely belated reply.

I was trying to get this working again and realized if I took the lines defining quoted_string from here:

https://github.com/pyparsing/pyparsing/blob/ee50a19dab1775e763c920e5e12f7e896b255ebd/pyparsing/core.py#L6097C1-L6104C58

and adding it to my example above then changed it slightly to set a name for the `MatchFirst` part, i.e. something like this:
```python
quoted_string = Combine(
    ((Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
     | (Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
         "single quoted string"
     )).set_name("string with quotes")
).set_name("quoted string using single or double quotes")
```
I get something much more useful, i.e.:

<img width="709" alt="Screenshot 2024-08-25 at 3 58 07 PM" src="https://github.com/user-attachments/assets/51184795-0922-4c08-b425-c7633426287a">

another approach was to move the `Combine` inside the `MatchFirst` i.e.:
```python
quoted_string = (
    Combine(
        Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"'
    ).set_name("double quoted string")
    | Combine(
        Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'"
    ).set_name("single quoted string")
).set_name("quoted string using single or double quotes")

```
giving:

<img width="738" alt="Screenshot 2024-08-25 at 5 10 11 PM" src="https://github.com/user-attachments/assets/e8ee7772-7711-4851-aab5-357404288d85">

Which reads a little better to me and may be the approach I'll use in my specific case.

It then occurred to me, considering your comment, that extracting elements without names may not be useful in general and maybe it is best to avoid?  Having a bit of a poke around the source code I found that one small change prevents extracting these unnamed elements, in this cases at least (i.e. at the second encounter), and seems like a possible acceptable solution as far as I can tell (tests still past, etc.).

i.e. change:
https://github.com/pyparsing/pyparsing/blob/ee50a19dab1775e763c920e5e12f7e896b255ebd/pyparsing/diagram/__init__.py#L516

to:
```python
        if el_id in lookup and lookup[el_id].name is not None:
```
It should be noted that the output is not in the same order (I'm assuming because the child elements, single/double quoted string, are not reached until later in the process).

**Comment by ptmcg** [comment]
I gave this a try, and it looks like it cleans up at least some of my empty diagram elements - thanks!  Adding it to the work for 3.2.0.

**Comment by ptmcg** [comment]
Weeelllll, this might not be the fix I'd hoped - and it adds another layer to the puzzle. Tests pass on Windows but fail on Linux with an InfiniteRecursionError... very odd to see OS-sensitive behavior, since pyparsing is pure Python. I need to rebuild all the Pythons on this particular Ubuntu box since I just upgraded it to latest LTS version. Will keep you updated.

**Comment by ptmcg** [comment]
Ok, not so bad news - the same test fails on both Windows and Linux, and in the same way. And the even better news is that this failed on a test that I _just added a couple of weeks ago_ (so this could have slipped through to release).  The issue is that, when building a diagram for an especially complex parser (the Lox language parser), it goes into an infinite recursion.

You can pull the latest master branch if you want to try it for yourself. At the moment, the day job beckons.

**Comment by RoDuth** [comment]
Thanks for taking a look.  Not that I think it matters but I'm running on a mac and it also fails as you suggest.

I think the main concern with that test is that `autoname_elements()` fails as its not within the correct frame being in `main()`, i.e. in `lox_parser.py` this fixes it and the test passes:
```diff
program.ignore(pp.dbl_slash_comment)
+pp.autoname_elements()

 def main():
-    pp.autoname_elements()
```
the railroad is generally a lot nicer also, except for this gobbledygook:

<img width="1689" alt="Screenshot 2024-09-06 at 12 08 25 PM" src="https://github.com/user-attachments/assets/8bc2546b-987f-4b6a-81b6-925ecc1e5aa9">
is this the last part of the infix_notation?

And the missing `MatchFirst` from this empty NOT:
<img width="418" alt="Screenshot 2024-09-06 at 12 12 36 PM" src="https://github.com/user-attachments/assets/3e7faa20-a490-4034-8da1-5cd7441b9b05">
Interestingly its not empty if you do this:
```diff
-keyword = pp.MatchFirst(keywords)
+keyword = CLASS | FUN | VAR | FOR | IF | ELSE | PRINT | RETURN | WHILE | TRUE | FALSE | NIL | THIS | SUPER | AND | OR
```
which gives what you'd expect:
<img width="508" alt="Screenshot 2024-09-06 at 12 18 12 PM" src="https://github.com/user-attachments/assets/5cfb2a9a-160a-4422-a2c0-9dbeb58c9d73">
Not that I have much of a clue why!  Although, when using `MatchFirst(keywords)`, I did notice that in `_to_diagram_element` `exprs` was an empty list and hence was returning None.

https://github.com/pyparsing/pyparsing/blob/dece4599751adae8becbcb80d8d02ddf9a81d748/pyparsing/diagram/__init__.py#L538-L540

**Comment by ptmcg** [comment]
Yep, `MatchFirst(keywords)` turned out to be non-functional, since the map() generator was never actually consumed! Also, the negative lookahead to avoid interpreting a keyword as an identifier turns out to be unnecessary, so the identifier definition cleans up considerably.

Also, thanks for the catch on the misplaced call to `autoname_elements()`!

As for the gobbledegook, this can often be cleaned up by adding some explicit calls to `set_name()` , though `infix_notation` generates a number of internal expressions too.

With these changes, I think we have a working lox_parser.py again (as soon as I check in the changes). Thanks for your help!

**Comment by RoDuth** [comment]
That looks much better, great work @ptmcg, more than happy to have played a minor part!

Pyparsing is 'the duck's nuts' as we say down here.
