### ISSUE TITLE
More regressions since 3.0.9

### ISSUE THREAD

**Issue by lemenkov** [pyparsing/pyparsing#555]
Hello!
I've stumbled upon more issues while trying to build [eerimoq/asn1tools](https://github.com/eerimoq/asn1tools). While it passes all the tests with 3.0.9 it generates the following errors (see file attached) with the recent pyparsing. These messages sounds very cryptic to me I must admit :)

[builder-live.log.txt](https://github.com/pyparsing/pyparsing/files/15310502/builder-live.log.txt)

**Comment by ptmcg** [comment]
I cloned this repository, and all the functional tests that parse the examples work fine. The test failures are all fairly cosmetic, failing on changes in the content of exception messages (which is not surprising since there were changes in both 3.1.1 and 3.1.2 to clean up messages, and try to make them more precise in indicating where an error occurred).

I've added some automation in my own testing to pull in the unit tests for asn1tools, so that I can run them against future versions of pyparsing before they get released.

**Comment by ptmcg** [comment]
These are in the release notes for 3.1.2:

- Fixed empty error message bug, PR submitted by InSync (#534). This _should_ return
  pyparsing's exception messages to a former, more helpful form. If you have code that
  parses the exception messages returned by pyparsing, this may require some code
  changes.

**Comment by lemenkov** [comment]
> I cloned this repository, and all the functional tests that parse the examples work fine. The test failures are all fairly cosmetic, failing on changes in the content of exception messages (which is not surprising since there were changes in both 3.1.1 and 3.1.2 to clean up messages, and try to make them more precise in indicating where an error occurred).
> 
> I've added some automation in my own testing to pull in the unit tests for asn1tools, so that I can run them against future versions of pyparsing before they get released.

@ptmcg thanks for the explanation! I'll try to address these ones.

**Comment by lemenkov** [comment]
Ok, I've fixed the error messages in asn1tools just for version 3.1.2 so I think I should close this.
