### ISSUE TITLE
Ambiguous parsing problem cannot be solved with FollowedBy - am I doing something wrong?

### ISSUE THREAD

**Issue by thirstydev** [pyparsing/pyparsing#563]
I have a simple example to illustrate this:

```
from pyparsing import oneOf, StringEnd, FollowedBy, PrecededBy

token1 = oneOf(["A", "ABC"])
token2 = oneOf(["BCA"])
parser = (token1 + token2)

# Testing the parser
try:
    result = parser.parseString("ABCA")
    print("Parsed successfully:", result.asList())
except Exception as e:
    print("Failed to parse:", str(e))

gives:
Failed to parse: Expected BCA, found 'A'  (at char 3), (line:1, col:4)
```

The parser (rightfully) consumes `ABC` (because of how `oneOf` reorders the terms, I think) to leave only `A` left, which can't be matched with `BCA`. I would've liked pyparsing to backtrack on its `oneOf` choice after realizing that choosing `ABC` fails and `A + BCA` is the right solution.

I thought using FollowedBy would have `oneOf` fail here:

```
parser = (token1 + FollowedBy(token2) + token2)
```

But it didn't work either. Using literal + `FollowedBy` works:

```
# Define the tokens
toks = ["A", "ABC"]
token2 = oneOf(["BCA"])

parser = MatchFirst([Literal(tok) + FollowedBy(token2) + token2 for tok in toks])
...
Parsed successfully: ['A', 'BCA']
```

However, I would think this creates a very large parse tree and does not scale with the number of choices in `token1` (is this assumption wrong?) as opposed to the `oneOf` method. I can't tell if this is a bug with `oneOf + FollowedBy` - is this what it's doing?

1. oneOf + FollowedBy matches because this will not be greedy and find that A + BCA works, so it allows the parse to continue
2. oneOf immediately chooses ABC greedily, and ends up failing to parse

Is there a way for 2 to be this?

2 (new). Use the match from 1. to continue 2. so we can match A + BCA instead of ABC

**Comment by ptmcg** [comment]
Unlike regex, pyparsing doesn't do backtracking.

`one_of` (`oneOf` is an old compatibility synonym, I recommend using the PEP-8 named `one_of`) is just a shortcut for doing a `MatchFirst` of the literals passed in, after reordering to guard against accidental masking of a longer literal by a shorter one. And as you have found, once the `MatchFirst` created by `one_of("A ABC")` matches the leading "ABC", then pyparsig proceeds with the next term, failing to find "BCA" when there is just the trailing "A".

`FollowedBy` isn't really doing anything in option 2, and can be removed and still successfully parse "ABCA" and "ABCBCA". What is actually making this work is that you are no longer just evaluating "A" vs "ABC" in the first token, but "A" and then "BCA" vs "ABC" and then "BCA".

```python
token1 = one_of(["A", "ABC"])
token2 = Literal("BCA")  # no need for one_of here
parser = (token1 + token2) ^ ("A" + token2)

parser.run_tests("""\
    ABCA
    ABCBCA
""")
```

Generally, I would suggest resolving ambiguous parsers using `Or` in place of `MatchFirst` or `one_of`. Unlike `MatchFirst`, `Or` (as emitted when using "^" instead of "|" or `one_of`) evaluates all the alternative expressions given and selects the one with the longest match.

This is probably a slightly better approach - notice how adding "AB" and "ABB" as additional options works with `Or` - with `MatchFirst`, this would start to get pretty messy, especially with less simple ambiguities:

```python
toks = ["A", "AB", "ABC", "ABB"]
token2 = Literal("BCA")
parser = Or(tok + token2 for tok in toks)

parser.run_tests("""\
    ABCA
    ABCBCA
    ABBCA
    ABBBCA
""")
```

In the absence of backtracking, and in the face of an ambiguous grammar such as this, the exhaustive enumeration of combinations of the ambiguous tokens is unavoidable with `pyparsing`. (Some other parsing package that might be more amenable to backtracking might be `lark` or `parsimonious`).

**Comment by ptmcg** [comment]
No further discussion added, closing.
