### ISSUE TITLE
seeing ` ImportError: cannot import name 'Set' from 'pyparsing'` issue in 3.2.0 release

### ISSUE THREAD

**Issue by chenrui333** [pyparsing/pyparsing#576]
👋 seeing ` ImportError: cannot import name 'Set' from 'pyparsing'` in 3.2.0 release, while 3.1.4 works fine.

relates to https://github.com/Homebrew/homebrew-core/pull/194190

**Comment by ptmcg** [comment]
"Set" is defined in the stdlib `typing` module, and should not be imported from pyparsing.

3.1.4 did import `Set` from `typing`, but no longer does so, now that the builtin `set` is provided in Python 3.9.  Pyparsing 3.2.0 requires Python 3.9.

I think this line indicated in traceback should be changed to import Set from `typing` (or if sigma-cli gets configured to support only Python 3.9 and later, then references to `Set` from `typing` can be changed to use the `set` builtin).

**Comment by ptmcg** [comment]
Yes, this should actually be fixed in the pySigma project. It already imports a number of names from typing, so removing Set from the pyparsing import and moving it to the typing import will fix one aspect of this problem.

But the bigger problem is that pySigma's pyproject.toml indicates that it supports Python back to 3.8, and pyparsing 3.2 does not do that. Even if you fix the Set import, pyparsing's use of builtins list, set, dict, etc. instead of List, Set, and Dict means that other code will break when run on Python 3.8.

At that point, pySigma will need to either drop support for Python 3.8 (it is past EOL), or pin the pyparsing dependency to <3.2 (perhaps using the ~=3.1 version marker, which will accept any 3.1.x version, but not 3.2).

**Comment by ptmcg** [comment]
Closing as resolved.
