### ISSUE TITLE
Parsing lists of objects instead of just strings of characters?

### ISSUE THREAD

**Issue by esawtooth** [pyparsing/pyparsing#73]
Today I made use of this awesome library to parse a list of divs while scraping a webpage. This webpage did not have sufficient structure _in situ_, but I was able to construct a string that pointed to the independent elements and parse that string based on a custom grammar. Mapping the parse tree back for that string gave me the parse tree for my divs. 

This got me thinking about if there might be any value in being able to parse lists of arbitrary objects instead of just strings of characters? All of my hacking then to maintain a 1:1 mapping between my object and a string representation would be unnecessary. It might also be more efficient if we could do this directly. Do you think there would any value in supporting such a scenario (or even if there is a better way to do something like this)?

**Comment by cngkaygusuz** [comment]
If you have a multi-level grammar tree (which is most probably the case), you are already parsing objects, its just the act of parsing starts from some sort of serialized data.

If you are asking to not have the leaves of the grammar tree to not be based on text/binary data but objects, then I struggle to see any reason for it. If there is a need for parsing, it implies there is a structured data converted into a format that is suitable for _communication_. A data structure may be serialized in binary, in which case it can be sent over the network to another computer. Source code is formatted in text, for facilitating the communication of intent between a human being and a computer. 

I cannot imagine the all-object representation of structured data to be useful for anything. For the purposes of communication, any sort of serialize-to-objects and parse-from-objects would be inferior to directly passing the parse tree (e.g., to a function). 

To better understand your example, showing some code would help. From what I gather, I can say you are first parsing a loosely-defined data _manually_, making it rigidly structured, writing it to text and then using pyparsing to parse it properly. What you are doing here is actually modifying the parse tree once you have it, and this task is something else in its entirety. 

On the other hand, I would also suggest using XPath to parse HTML pages (check out lxml). Using custom parsers to parse HTML is a tedious process, prone to error, and there is little chance your code will work if your target page changes.

**Comment by ptmcg** [comment]
I wouldn't be quite so harsh about using pyparsing for scraping web pages. Unlike parsers like BeautifulSoup and elementTree, pyparsing does not assume that you are trying to parse the *entire* page of HTML into a hierarchical model. Instead you can scan the HTML and slice out the bits that are of particular interest. This is especially helpful when the site uses HTML that is troublesome in some regard, insofar that it defies being parsed into a single document hierarchy from the complete page. In this case, pyparsing can be written to sidestep, or even utilize those problem sections, since in your grammar you are not constrained to create a fully valid HTML grammar.

The other point about using pyparsing's builtin makeHTMLTags method, it is very tolerant of many of the variabilities that make HTML parsing fragile (especially with tools such as regex). makeHTMLTags will return expressions that can handle a variety of tag attributes, including: upper and lower case tag and attribute names; attribute values with and without enclosing quotation marks or apostrophes; opening tags with and with out a '/' self-closer. And of course, unpredictable whitespace, since pyparsing just skips over it.

As for the OP's original comment about creating parsers for some form of object stream, I have actually had a similar proposal in the past, at a PyCon in Dallas. In practice, I think the best you could do would be to mimic pyparsing's approach in defining the objects you wish to process, with alternation and conjunction of object types at various points in the object "grammar", with your object matching log modelled with an embedded DSL using arithmetic or logical operators. You would then need to implement your own form of "object stream", which could be an in-memory data structure (maybe as simple as a list), or maybe a cursor returned by a database query. But even so, this idea is kind of "out there". Pyparsing is able to ride on top of some pretty common and popular structures and object types (strings and characters), so writing a generic parsing library is not an unnatural thing.

Think about what kinds of objects and object streams might be as generic as text in a string. A few do come to mind. To really be good candidates, they should be generic, have some notion of ordering or sequence, be definable using some form of pattern, and be applicable across different domains. Some ideas:

- tasks in a task schedule

- nodes in a graph

- documents matching a search query (a weak candidate, since query results are probably not strongly ordered)

Or you might find that pyparsing would parse some body of text (such as an application or system log), produce a stream of objects, and then you could apply some object-level grammar to them.

In any event, thanks for posting your idea. I can't take you up on it myself just now, but if you start a project of your own, I'll be happy to follow and remark on it.

-- Paul

**Comment by klahnakoski** [comment]
This is an interesting proposal.  From my perspective, if this was possible, it seems like pyparsing would be doing two things:  

1.  it would be verifying some rules; maybe a grammar is a more elegant way to specify structural rules? I have not thought this through, and maybe there is opportunity there.  
2.  pyparsing would be (re) assembling the source structure into something more useful to the consuming program. Much of my work appears to be translating one data structure into another; I consider this a big domain, and maybe there is opportunity here too. Again, more thought is required.

For example, fastparquet uses a [thrift specification for the parquet file format](https://github.com/dask/fastparquet/blob/master/fastparquet/parquet.thrift).  Thrift is yet-another-parser-specification-language, and it does not seem to go far enough:  A good part of the fastparquet code is spent navigating the parsed structure.  When I see lots of data navigation code I can't help but to think the data is in the wrong shape for what is being done.  Maybe higher level parsing would help with this.

This is all wild speculation.  I will try to keep this in the back of my mind, and see if I stumble upon an example.

**Comment by ptmcg** [comment]
At this point, I think this is more of a discussion thread rather than an actual issue, so I'm going to close it.

Probably good material to post on the new pyparsing sub-reddit if there is further discussion.
