### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by Freakwill** [pyparsing/pyparsing#82]
Following is the test code. Is it a bug? It confused me.

```python
p = (Literal('=')| '\\' + Literal('eq'))('sign')
r = p.parseString('=')
print(r.sign)
# => ['=']
```

```python
p = (Literal('=')| Literal('eq'))('sign')
r = p.parseString('=')
print(r.sign)
# => '='
```

**Comment by ptmcg** [comment]
from pyparsing import *

For an Or or MatchFirst expression (`^` or `|` operators), pyparsing will return a list if any of the alternatives can return a list. This is intentional behavior. Otherwise, your post-parsing code would have to add type checking to see whether a list or str was parsed out of the given input.


    p = (Literal('=')| '\\' + Literal('eq'))('sign')
    p.runTests(r"""\
        =
        \eq
    """)

Prints:

    =
    ['=']
    - sign: ['=']


    \eq
    ['\\', 'eq']
    - sign: ['\\', 'eq']

So for this particular expression, all input strings will return a list, even if match only required matching a single expression.

    p = (Literal('=')| Literal('eq'))('sign')
    p.runTests("""\
        =
        eq
    """)

Prints:

    =
    ['=']
    - sign: '='


    eq
    ['eq']
    - sign: 'eq'

For this expression, all alternatives will return just a string, so a simple non-list string can be returned.

If `\` is supposed to be the leading character of `\eq`, then you can change to `Combine('\\' + Literal('eq'))`, and this will always return a string, not a list (by joining all the matched elements inside the Combine).
