### ISSUE TITLE
pyparsing performance with tab

### ISSUE THREAD

**Issue by ws1088** [pyparsing/pyparsing#88]
have you guys experienced that the same parser performs slower if the input file is of TAB instead of space?

for example, file content is:
abc = 3
edf = 4

of course the file needs to be very large (like 50k lines)

if the parser is simply:

rule = Suppress(LineStart() + SkipTo(LineEnd) + LineEnd())

sed "s/ /\t/g" file > file_tab
sed "s/\t/ /g" file > file_space

**Comment by ptmcg** [comment]
By default, `parseString` will call `str.expandtabs` on the given string, so that parsers with column-significant elements will compute correct column numbers. The performance difference you are seeing may be due to this upfront conversion of tabs to spaces.

If you do not have any elements in your parser that depend on items being in particular columns, then you can call `expr.parseWithTabs()` before calling `expr.parseString`.

**Comment by ws1088** [comment]
thanks for the explanation. yup, that's the reason which cause the slowness. thanks!
