### ISSUE TITLE
Unexpected behaviour with Or and addCondition

### ISSUE THREAD

**Issue by dvzubarev** [pyparsing/pyparsing#93]
Hi, 
please, see the code:
```import pyparsing as pp
w = pp.Word(pp.alphas)
parser = pp.Or([w('1') + w.addCondition(lambda t : t[0].endswith("aaa")),
                w('2') + w])

#the first case
m = parser.parseString('temp tempaaa')
print (m.dump())
# std out:
#['temp', 'tempaaa']
#- 1: 'temp'

#the second case
m = parser.parseString('temp temp')
print (m.dump())
#exception:
#pyparsing.ParseException: Expected {{W:(ABCD...) W:(ABCD...)} ^ {W:(ABCD...) W:(ABCD...)}} (at char 5), (line:1, col:6)
```
I expected that the second pattern of Or would match in the second case. But instead I got an exception. Is it expected behaviour?
pyparsing 2.4
python 3.6.7

**Comment by paulmcg-iio** [comment]
`w.addCondition` will modify `w` in place, so your second alternative in your `Or` is just the same as the first. Try `w().addCondition` instead, so that you modify and use a copy of `w` in your first alternative, leaving the `w` in the second alternative conditionless.

**Comment by dvzubarev** [comment]
Thank you, I thought that `addCondition` returns a copy of w.

**Comment by dvzubarev** [comment]
Sorry to disturb again, but I try to debug another `addCondition` issue. Please see the code.
```
import pyparsing as pp

ws = pp.Word(pp.alphas)
ws.addCondition(lambda t : t[0].endswith("-suffix"))

alt1_1 = ws('1.1') + pp.Word(pp.alphas)('1.2')
alt1_2 = pp.Word(pp.alphas)('1.3')
alt1 = pp.Or([alt1_1, alt1_2])
alt1 = pp.Word(pp.alphas)('1') + alt1

alt2 = pp.Word(pp.alphas)('2.1') + pp.Word(pp.alphas)('2.2') + pp.Word(pp.alphas)('2.3')

parser = pp.Or([alt1, alt2])

m = parser.parseString('foo bar temp')
print (m.dump())

#std out:
# ['foo', 'bar']
# - 1: 'foo'
# - 1.3: 'bar'
```
I would expect that `alt2` will match, since it is longer than `alt1_2`. `alt2` is matched if I remove `alt1_1`, but it is quite surprising to me.
`alt2` is also matched, if I change `alt1` a little: 
```
alt1 = pp.Or([pp.Word(pp.alphas)('1') + alt1_1, pp.Word(pp.alphas)('1') + alt1_2])
```

But it seems that it should be equivalent to 

```
alt1 = pp.Or([alt1_1, alt1_2])
alt1 = pp.Word(pp.alphas)('1') + alt1
```

**Comment by ptmcg** [comment]
The issue you are seeing here is the timing of matching vs. evaluating the added condition. The default behavior is for Or to evaluate all the given alternatives *without* running any parse actions or conditions. It then reparses all the alternatives that matched, in order of longest match to shortest, this time evaluating parse actions and conditions. So you can see that an Or can be a time-consuming element to have in your parser.

I reworked your example into something I could more easily read:

    word = pp.Word(pp.alphas).setName('word')
    word_1 = pp.Word(pp.alphas).setName('word_1').addCondition(lambda t: len(t[0]) == 1)

    a = word + (word_1 + word ^ word)
    b = word * 3
    c = a ^ b

Like your `ws` expression, whose added condition will prevent it from matching any of the words in the input string, `word_1` will match any alpha word but then fail if the word is longer than 1 character.

I then enabled debug on the a and b expressions, so that all parser match start, end, and fails would be logged:

    a.setDebug()
    b.setDebug()

The names on `word` and `word_1` will help make the debugging output easier to follow.

Finally I print out the resulting `c` parser, after calling `streamline()` (which collapses down `(a ^ b) ^ c` expressions to `a ^ b ^ c`).

    c.streamline()
    print(c)

Calling the parser with:

    print(c.parseString('foo bar temp'))

Gives (I've added annotations with '#' characters):

    # the parser
    {{word {{word_1 word} ^ word}} ^ {word word word}}
    
    # try to match all alternatives a and b - both will succeed, and both
    # match the same length of input
    Match {word {{word_1 word} ^ word}} at loc 0(1,1)
    Matched {word {{word_1 word} ^ word}} -> ['foo', 'bar', 'temp']
    Match {word word word} at loc 0(1,1)
    Matched {word word word} -> ['foo', 'bar', 'temp']

    # Now retry the parse in descending order of length, this time evaluating
    # parse actions and conditions.
    Match {word {{word_1 word} ^ word}} at loc 0(1,1)
    
    # Now `word_1` does not match, but the inner alternative still matches, 
    # giving `['foo', 'bar']` as the result. Since this was previously picked
    # as the highest priority match, 
    Matched {word {{word_1 word} ^ word}} -> ['foo', 'bar']
    ['foo', 'bar']

Unfortunately, `Or` returns the `['foo', 'bar']` match before trying any other matches to see if one of them might be longer.

Now let's look at the other form that you tried, in my simplified form, it is equivalent to:

    a = (word + word_1 + word) ^ (word + word)

pyparsing's streamline code converts the parser c to:

    {{word word_1 word} ^ {word word} ^ {word word word}}

And the debugging log is easy to follow:

    # first try all 3 alternatives without running added conditions
    Match {word word_1 word} at loc 0(1,1)
    Matched {word word_1 word} -> ['foo', 'bar', 'temp']
    Match {word word} at loc 0(1,1)
    Matched {word word} -> ['foo', 'bar']
    Match {word word word} at loc 0(1,1)
    Matched {word word word} -> ['foo', 'bar', 'temp']

    # retry the expressions in descending length order
    
    # Now this alternative that includes `word_1` won't even match
    # so it is dropped
    Match {word word_1 word} at loc 0(1,1)
    Exception raised:failed user-defined condition (at char 4), (line:1, col:5)

    # The next longest match succeeds, and so is selected as the matching
    # expression
    Match {word word word} at loc 0(1,1)
    Matched {word word word} -> ['foo', 'bar', 'temp']
    ['foo', 'bar', 'temp']

You could force pyparsing to use the filtering condition during the first pass if you include `callDuringTry=True` argument to `addCondition`:

    ws.addCondition(lambda t : t[0].endswith("-suffix"), callDuringTry=True)

Adding this change to the simplified form gives this debugging output:

    Match {word word_1 word} at loc 0(1,1)
    Exception raised:failed user-defined condition (at char 4), (line:1, col:5)
    Match {word word} at loc 0(1,1)
    Matched {word word} -> ['foo', 'bar']
    Match {word word word} at loc 0(1,1)
    Matched {word word word} -> ['foo', 'bar', 'temp']
    Match {word word word} at loc 0(1,1)
    Matched {word word word} -> ['foo', 'bar', 'temp']
    ['foo', 'bar', 'temp']

Now the Or just has to choose between the 2-word or 3-word match.

Based on your post, I have some code that I will add in the next release to make `Or` behave a little smarter, and do a better job at consistently matching longest matches.

-- Paul

**Comment by dvzubarev** [comment]
Thank you for the thorough explanation! I didn't know about those debug tools, they will make debugging much easier.
