### ISSUE TITLE
Modifying existing rules

### ISSUE THREAD

**Issue by davidtr1037** [pyparsing/pyparsing#96]
Is it possible to update an existing rule?
Let's sat E = infixNotation(E, ...), with E = Word("ab").
Is it possible to change the rule to E = Word("abc") without re-defining all it's dependent rules?

**Comment by ptmcg** [comment]
Do you mean you want to do this dynamically at runtime? Yes it is possible, with a little preparation.

First off, your sample uses E for both the operand for infixNotation and for the result from infixNotation. This is generally not a good idea, and I'm not sure why you would do this. Secondly, when you write `Word("ab")` that is not the same as parsing the literal "ab" - this expression will match any wordgroup (space-delimited characters) made up of 'a' and 'b' characters. While this *would* match "ab", it will also match "aaaa", "bbbb", "baba", and so on. If you want to match just "ab", use `Literal("ab")` (as shown in the following example for the literals "START" and "END").

So let's move away from your specific example, and just talk about an expression that is dynamic at runtime.

To do this, define your parser using a Forward as a placeholder, and set it to your original `Word("ab")` expression:

    placeholder = Forward()
    placeholder <<= Word("ab")

Then you use placeholder in some other parts of your parser.

    x = Literal("START") + placeholder + Literal("END")

so that you can now parse strings like "START aaa END", "START bbb END", and "START bbaabbaa END". Now somehow, at runtime, you determine that the word should really allow for 'c' characters too, so you'd like to replace the contents of the placeholder with `Word("abc")`. Just do this:

    placeholder <<= Word("abc")

Now all the places where placeholder is used will use the new `Word("abc")` expression.

Did I understand your question rightly? Or did I answer something completely different, and just confuse you further?

**Comment by davidtr1037** [comment]
Yes, thanks. I meant something like A = infixNotation(E, ...) (was a typo).
Just to make sure, after doing 
```
"placeholder <<= Word("abc")" 
```
the old definition of E (that is, Word("abc")) will not be used any more, right?

Another (related) question:
I define a infixNoration with many operators (~20) and as you may guess, it affects the performance (I am using packrat).
Is it possible to set dynamically the relevant operators?
For example if the input text contains only '+' and '-' operators (by simple text search), then I want to remove the rest from the list which is passed to the infixNotation.
I guess the Forward trick can do it, but is there another way?

**Comment by ptmcg** [comment]
Let's try it and see:

    import pyparsing as pp

    dynamic = pp.Forward()
    expr1 = pp.Word('ab')
    expr2 = pp.Word('abc')

    tests = """\
     abbab
        abbcabbc
        ccc
        aaa
        bbb
        """

    for expr in (expr1, expr2):
        dynamic <<= expr
        print("Using", expr)
        dynamic.runTests(tests)
        print()

Prints:
    
    Using W:(ab)
    abbab
    ['abbab']

    abbcabbc
       ^
    FAIL: Expected end of text (at char 3), (line:1, col:4)

    ccc
    ^
    FAIL: Expected W:(ab) (at char 0), (line:1, col:1)

    aaa
    ['aaa']

    bbb
    ['bbb']

    Using W:(abc)
    abbab
    ['abbab']
    
    abbcabbc
    ['abbcabbc']
    
    ccc
    ['ccc']
    
    aaa
    ['aaa']
    
    bbb
    ['bbb']

`runTests()` makes it easy for you to do experiments and regression tests for yourself.
    
As for dynamically constructing your `infixNotation` list of operators, that is certainly possible - the second argument to `infixNotation` is just a list of tuples, so you can create that however you like based on the input string, and then use the resulting list in your call to `infixNotation`. But you might have some other part of your parser that is slowing things down, such as using `Combine()` to build up a numeric expression out of integer pieces before and after a decimal point - use `pyparsing_common.integer` or `pyparsing_common.number` instead, they will parse much faster.
